In [1]:
import pandas as pd

In [2]:
data = pd.read_excel("AI Scholarship Registration (Responses)(1).xlsx")

In [3]:
data

,Timestamp,Name,Phone Number ( must have WhatsApp ),Email,Please Select Preferred Scholarship type,LinkedIn,Please upload your CV,Why do you want this Scholarship?,Why should we accept you?,Where did you hear about us?,Preferred Sessions Time,What are the topics that you want to learn during this scholarship ?,Any notes
0,2026-01-23 17:25:09.672,Abdelrahman Khalil Ali Mohamed,01111070574,kabdelrahman213@gmail.com,Online,https://www.linkedin.com/in/abdelrahman-khalil...,https://drive.google.com/open?id=1OXEUPDVvHFER...,It will help me to get job,..,Facebook,Any time is ok,"Python Basics, Mathematics, Data Preprocessing...",..
1,2026-01-23 17:28:36.010,Samy Haliem,01227531720,samy.scomi@gmail.com,Online,https://www.linkedin.com/in/samyhaliem/,https://drive.google.com/open?id=1MA5qC-xYVIQl...,Carrier change,Because i love to learn,Facebook,Night,"Data Preprocessing, Data Analysis ( using pyth...",No thanks
2,2026-01-23 17:28:36.188,Rehab Abuelhassan Mohamed,01064713782,rehababuelhassan6@gmail.com,Online,www.linkedin.com/in/rehab-abuelhassan-21973b21...,https://drive.google.com/open?id=10apviXBsA4_G...,to learn,because I have some experience,Facebook,Night,"Python Basics, Mathematics, Data Preprocessing...",no
3,2026-01-23 17:30:02.485,ايات محمد فخرى محمد,01095103433,Ayatfakhary4@gmail.com,Hybrid,https://www.linkedin.com/in/ayat-fakhary-614ab...,https://drive.google.com/open?id=1SfFCARr254f_...,علشان حابة اتعلم كل مجال ال ai وكل المجالات ال...,Because I want to learn and I love this track ...,Facebook,Any time is ok,"MLOps ( using AWS and/or Huwawie Cloud ), NLP ...",حابة استفيد من المنحة واتعلم التراكات دى لان و...
4,2026-01-23 17:30:23.532,Abdelghany Ahmed Elshershapy,01552256981,abdelghany662002@gmail.com,Hybrid,https://www.linkedin.com/in/abdelghany-elshers...,https://drive.google.com/open?id=1PMchgyyWjbK0...,Because I want to land on a new job on AI fiel...,As I am self studied person who want to improv...,AItronix (currently student with them),Any time is ok,Introduction to Data Engineering ( Theoratical...,Thanks for this opportunity and I hope to be o...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
412,2026-04-02 05:35:08.338,yousef mohammed abdelkareem,01123277241,ym9159303@gmail.com,Offline,https://www.linkedin.com/in/joox/,https://drive.google.com/open?id=1Se11E-QMzEsz...,I'm a Computer Science student at Helwan Unive...,I'm not starting from zero — I already have pr...,aitronix round4,Any time is ok,"Machine Learning, Deep Learning, MLOps ( using...",naaaa
413,2026-04-06 05:32:48.638,Abdullah Abdelhakeem Sabrah,01008995928,abdosabrah49@gmail.com,Online,linkedin.com/in/abdullah-abdelhakeem-sabrah-b2...,https://drive.google.com/open?id=1TLjHveMSCeds...,"I service had ended at military, i am searchin...",I think that what i have now so i will do my b...,Linkedin,Night,Introduction to Data Engineering ( Theoratical...,Thanks
414,2026-04-08 19:03:59.348,Tarek Amr Mostafa,01129886261,tarekamr737@gmail.com,Online,https://www.linkedin.com/in/tarek-amr737?utm_s...,https://drive.google.com/open?id=14KwYu3eZFsBu...,"As a senior AI Engineering student, this schol...",You should accept me because I have a solid AI...,LinkedIn,Night,"MLOps ( using AWS and/or Huwawie Cloud ), NLP ...",I am highly motivated to expand my expertise i...
415,2026-04-11 21:53:29.407,Mohamed Amir Abouzaid Ahmed,01013390569,mohamedamirezz05@gmail.com,Online,https://www.linkedin.com/in/mohamed-amir-55727...,https://drive.google.com/open?id=1eMIahbsGNFwh...,My goal is to learn and apply my knowledge to ...,I am passionate about learning and delving dee...,Facebook,Morning,"Data Preprocessing, Introduction to Data Engin...",Please indicate if the dates are subject to ch...
416,2026-04-14 18:15:15.363,Rama Abdelgadir Imam MohamedAhmed,01123240218,Ramaabdelgadir@gmail.com,Hybrid,Linkedin.com/in/rama-abdelgadir,https://drive.google.com/open?id=1WIOGEnQRli6z...,I want to strengthen my foundation in Artifici...,I have a strong background in AI with hands-on...,Linkedin,Any time is ok,"MLOps ( using AWS and/or Huwawie Cloud ), NLP ...",I am currently transitioning from project-base...

In [4]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 417 entries, 0 to 416
Data columns (total 13 columns):
 #   Column                                                                 Non-Null Count  Dtype
---  ------                                                                 --------------  -----
 0   Timestamp                                                              417 non-null    datetime64[us]
 1   Name                                                                   417 non-null    str
 2   Phone Number ( must have WhatsApp )                                    417 non-null    object
 3   Email                                                                  417 non-null    str
 4   Please Select Preferred Scholarship type                               417 non-null    str
 5   LinkedIn                                                               415 non-null    str
 6   Please upload your CV                                                  417 non-null    str
 7   Why do you want this Scholarship?                                      417 non-null    str
 8   Why should we accept you?                                              416 non-null    str
 9   Where did you hear about us?                                           417 non-null    str
 10  Preferred Sessions Time                                                417 non-null    str
 11  What are the topics that you want to learn during this scholarship ?   417 non-null    str
 12  Any notes                                                              391 non-null    str
dtypes: datetime64[us](1), object(1), str(11)
memory usage: 420.0+ KB

In [5]:
data.describe()

                        Timestamp
count                         417
mean   2026-02-04 21:31:18.352187
min    2026-01-23 17:25:09.672000
25%    2026-01-24 11:07:35.981000
50%    2026-01-29 19:35:06.962000
75%    2026-02-11 21:22:23.712000
max    2026-04-14 18:15:15.363000

In [6]:
data.describe(include= "object")

/var/folders/_r/3sb29fjj12d916yfxyrhd_gc0000gn/T/ipykernel_1105/1706952385.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  data.describe(include= "object")

,Name,Phone Number ( must have WhatsApp ),Email,Please Select Preferred Scholarship type,LinkedIn,Please upload your CV,Why do you want this Scholarship?,Why should we accept you?,Where did you hear about us?,Preferred Sessions Time,What are the topics that you want to learn during this scholarship ?,Any notes
count,417,417,417,417,415,417,417,416,417,417,417,391
unique,395,383,389,3,391,417,412,413,189,4,187,201
top,Mina Magdy Wessa Gendy,01020637552,minamagdy1270@gmail.com,Online,https://www.linkedin.com/in/mina-magdy-data-an...,https://drive.google.com/open?id=1OXEUPDVvHFER...,To improve my skills,"You should accept me because I am a committed,...",LinkedIn,Night,"Python Basics, Mathematics, Data Preprocessing...",No
freq,3,3,3,214,3,1,2,2,57,196,77,56

In [7]:
data.duplicated().sum()

np.int64(0)

In [9]:
data.Name.duplicated().sum()

np.int64(22)

In [14]:
data.groupby("Name").size().sort_values(ascending= False)

Name
Karam yahia sayed           3
Abdallah Ali Abdelgawad     3
Mohammad Ahmed Ayman        3
Mina Magdy Wessa Gendy      3
Mahmoud                     2
                           ..
Hassan Sherif               1
Hasnaa Marzouk              1
Hanya wael fawzy hussein    1
Hager abass                 1
هشام حمدى سعد أبوسعدة       1
Length: 395, dtype: int64

In [18]:
data.groupby("Name").size().sort_values(ascending= False)[:20]

Name
Karam yahia sayed                3
Abdallah Ali Abdelgawad          3
Mohammad Ahmed Ayman             3
Mina Magdy Wessa Gendy           3
Mahmoud                          2
Mohamed Mahmoud Abdelbasset      2
Laila Mohammad Abdulaziz         2
Ahmed Walid Ibrahim              2
Dina Ahmed El Sayed Fathy        2
Walid Ali Mahmoud Ali            2
Mohammed Mokhtar Ali Mohammed    2
Hayam Mostafa Abdelhamid         2
Mohamed Wael Mohamed Elsayed     2
Mariam Hany                      2
Mariam Mansour Albasyouni        2
Sahar Amr Elmadawey              2
Mohamed Abdel Tawwab Badr        2
Menna amr                        2
Omnia Hussein Ali Abdallah       1
Nada khaled Ahmed Bastawi        1
dtype: int64

In [21]:
duplicated_names = data.groupby("Name").size().sort_values(ascending= False)[:18].index.tolist()
duplicated_names

['Karam yahia sayed',
 'Abdallah Ali Abdelgawad ',
 'Mohammad Ahmed Ayman',
 'Mina Magdy Wessa Gendy',
 'Mahmoud',
 'Mohamed Mahmoud Abdelbasset',
 'Laila Mohammad Abdulaziz ',
 'Ahmed Walid Ibrahim',
 'Dina Ahmed El Sayed Fathy',
 'Walid Ali Mahmoud Ali ',
 'Mohammed Mokhtar Ali Mohammed',
 'Hayam Mostafa Abdelhamid',
 'Mohamed Wael Mohamed Elsayed',
 'Mariam Hany ',
 'Mariam Mansour Albasyouni ',
 'Sahar Amr Elmadawey ',
 'Mohamed Abdel Tawwab Badr ',
 'Menna amr ']

In [22]:
duplicated_dfs = {}

for name in duplicated_names : 
    duplicated_dfs[name] = data[data.Name == name]

In [23]:
duplicated_dfs["Karam yahia sayed"]

,Timestamp,Name,Phone Number ( must have WhatsApp ),Email,Please Select Preferred Scholarship type,LinkedIn,Please upload your CV,Why do you want this Scholarship?,Why should we accept you?,Where did you hear about us?,Preferred Sessions Time,What are the topics that you want to learn during this scholarship ?,Any notes
194,2026-01-28 22:05:45.602,Karam yahia sayed,01002059451,karamyahia46@gmail.com,Online,https://www.linkedin.com/in/karamyahia,https://drive.google.com/open?id=1-HzScCaGDgdg...,علشان انا بتعلم فى تراك الAiوحابب اخد المنحه م...,علشان انا محتاج المنحه دى ومعنديش المقدره انى ...,من صديق,Night,"Machine Learning, Deep Learning, MLOps ( using...",لا يوجد
195,2026-01-28 22:06:10.668,Karam yahia sayed,01002059451,karamyahia46@gmail.com,Online,https://www.linkedin.com/in/karamyahia,https://drive.google.com/open?id=1e3t7lQTr5eLn...,علشان حابب مجال Ai وحاليا بتعلم فى,علشان انا محتاج المنحه دى وفى المقابل معنديش إ...,من صديق لى,Night,"Mathematics, Introduction to Data Engineering ...",لا يوجد
209,2026-01-29 20:02:03.191,Karam yahia sayed,01002059451,karamyahia46@gmail.com,Online,https://www.linkedin.com/in/karamyahia,https://drive.google.com/open?id=1E4illS9j5bp9...,انا فى هندسه اتصالات وإلكترونيات ويدرس فى تراك...,لانى محتاج الكورس جدا وانا واخد اكتر من كورس ...,من صديق,Night,"Machine Learning, Deep Learning, MLOps ( using...",لا يوجد

In [24]:
duplicated_dfs["Abdallah Ali Abdelgawad "]

,Timestamp,Name,Phone Number ( must have WhatsApp ),Email,Please Select Preferred Scholarship type,LinkedIn,Please upload your CV,Why do you want this Scholarship?,Why should we accept you?,Where did you hear about us?,Preferred Sessions Time,What are the topics that you want to learn during this scholarship ?,Any notes
8,2026-01-23 17:37:29.635,Abdallah Ali Abdelgawad,1148660852,abdofarahat2006@gmail.com,Online,www.linkedin.com/in/abdallah-ali-da,https://drive.google.com/open?id=14Efa4v3d5XHT...,Cause It Will Help Me Alot In My Carrer Furthe...,"Because AM A STUDENT, I HAVE TIME FOR IT, AND...",I Already talked with Dr. Ahmed Before at AI f...,Night,Introduction to Data Engineering ( Theoratical...,Keep Going
200,2026-01-29 15:26:20.886,Abdallah Ali Abdelgawad,011 48660852,abdofarahat2006@gmail.com,Online,www.linkedin.com/in/abdallah-ali-da,https://drive.google.com/open?id=1LMqoCEqcmA9B...,To Improve My Skills & Add Experience,"First Related To It ,Have Some Knowledge & Time",in AI FOR X EVENT AND My Friends,Night,"Mathematics, Data Preprocessing, Data Analysis...",Keep Going
299,2026-02-11 18:15:01.814,Abdallah Ali Abdelgawad,1148660852,abdofarahat2006@gmail.com,Online,www.linkedin.com/in/abdallah-ali-da,https://drive.google.com/open?id=1xFu8mEV-Kz9T...,"improve my knowledge , make progress for my ca...",i already have relative knowledge,friend,Night,"Machine Learning, Deep Learning, MLOps ( using...",no keep going

In [26]:
data[ data.groupby("Name").size().sort_values(ascending= False)[:18].index.tolist()]

KeyError: "None of [Index(['Karam yahia sayed', 'Abdallah Ali Abdelgawad ', 'Mohammad Ahmed Ayman',\n       'Mina Magdy Wessa Gendy', 'Mahmoud', 'Mohamed Mahmoud Abdelbasset',\n       'Laila Mohammad Abdulaziz ', 'Ahmed Walid Ibrahim',\n       'Dina Ahmed El Sayed Fathy', 'Walid Ali Mahmoud Ali ',\n       'Mohammed Mokhtar Ali Mohammed', 'Hayam Mostafa Abdelhamid',\n       'Mohamed Wael Mohamed Elsayed', 'Mariam Hany ',\n       'Mariam Mansour Albasyouni ', 'Sahar Amr Elmadawey ',\n       'Mohamed Abdel Tawwab Badr ', 'Menna amr '],\n      dtype='str')] are in the [columns]"

In [27]:
new_data = data.set_index("Name" )
new_data

,Timestamp,Phone Number ( must have WhatsApp ),Email,Please Select Preferred Scholarship type,LinkedIn,Please upload your CV,Why do you want this Scholarship?,Why should we accept you?,Where did you hear about us?,Preferred Sessions Time,What are the topics that you want to learn during this scholarship ?,Any notes
Name,,,,,,,,,,,,
Abdelrahman Khalil Ali Mohamed,2026-01-23 17:25:09.672,01111070574,kabdelrahman213@gmail.com,Online,https://www.linkedin.com/in/abdelrahman-khalil...,https://drive.google.com/open?id=1OXEUPDVvHFER...,It will help me to get job,..,Facebook,Any time is ok,"Python Basics, Mathematics, Data Preprocessing...",..
Samy Haliem,2026-01-23 17:28:36.010,01227531720,samy.scomi@gmail.com,Online,https://www.linkedin.com/in/samyhaliem/,https://drive.google.com/open?id=1MA5qC-xYVIQl...,Carrier change,Because i love to learn,Facebook,Night,"Data Preprocessing, Data Analysis ( using pyth...",No thanks
Rehab Abuelhassan Mohamed,2026-01-23 17:28:36.188,01064713782,rehababuelhassan6@gmail.com,Online,www.linkedin.com/in/rehab-abuelhassan-21973b21...,https://drive.google.com/open?id=10apviXBsA4_G...,to learn,because I have some experience,Facebook,Night,"Python Basics, Mathematics, Data Preprocessing...",no
ايات محمد فخرى محمد,2026-01-23 17:30:02.485,01095103433,Ayatfakhary4@gmail.com,Hybrid,https://www.linkedin.com/in/ayat-fakhary-614ab...,https://drive.google.com/open?id=1SfFCARr254f_...,علشان حابة اتعلم كل مجال ال ai وكل المجالات ال...,Because I want to learn and I love this track ...,Facebook,Any time is ok,"MLOps ( using AWS and/or Huwawie Cloud ), NLP ...",حابة استفيد من المنحة واتعلم التراكات دى لان و...
Abdelghany Ahmed Elshershapy,2026-01-23 17:30:23.532,01552256981,abdelghany662002@gmail.com,Hybrid,https://www.linkedin.com/in/abdelghany-elshers...,https://drive.google.com/open?id=1PMchgyyWjbK0...,Because I want to land on a new job on AI fiel...,As I am self studied person who want to improv...,AItronix (currently student with them),Any time is ok,Introduction to Data Engineering ( Theoratical...,Thanks for this opportunity and I hope to be o...
...,...,...,...,...,...,...,...,...,...,...,...,...
yousef mohammed abdelkareem,2026-04-02 05:35:08.338,01123277241,ym9159303@gmail.com,Offline,https://www.linkedin.com/in/joox/,https://drive.google.com/open?id=1Se11E-QMzEsz...,I'm a Computer Science student at Helwan Unive...,I'm not starting from zero — I already have pr...,aitronix round4,Any time is ok,"Machine Learning, Deep Learning, MLOps ( using...",naaaa
Abdullah Abdelhakeem Sabrah,2026-04-06 05:32:48.638,01008995928,abdosabrah49@gmail.com,Online,linkedin.com/in/abdullah-abdelhakeem-sabrah-b2...,https://drive.google.com/open?id=1TLjHveMSCeds...,"I service had ended at military, i am searchin...",I think that what i have now so i will do my b...,Linkedin,Night,Introduction to Data Engineering ( Theoratical...,Thanks
Tarek Amr Mostafa,2026-04-08 19:03:59.348,01129886261,tarekamr737@gmail.com,Online,https://www.linkedin.com/in/tarek-amr737?utm_s...,https://drive.google.com/open?id=14KwYu3eZFsBu...,"As a senior AI Engineering student, this schol...",You should accept me because I have a solid AI...,LinkedIn,Night,"MLOps ( using AWS and/or Huwawie Cloud ), NLP ...",I am highly motivated to expand my expertise i...
Mohamed Amir Abouzaid Ahmed,2026-04-11 21:53:29.407,01013390569,mohamedamirezz05@gmail.com,Online,https://www.linkedin.com/in/mohamed-amir-55727...,https://drive.google.com/open?id=1eMIahbsGNFwh...,My goal is to learn and apply my knowledge to ...,I am passionate about learning and delving dee...,Facebook,Morning,"Data Preprocessing, Introduction to Data Engin...",Please indicate if the dates are subject to ch...
Rama Abdelgadir Imam MohamedAhmed,2026-04-14 18:15:15.363,01123240218,Ramaabdelgadir@gmail.com,Hybrid,Linkedin.com/in/rama-abdelgadir,https://drive.google.com/open?id=1WIOGEnQRli6z...,I want to strengthen my foundation in Artifici...,I have a strong background in AI with hands-on...,Linkedin,Any time is ok,"MLOps ( using AWS and/or Huwawie Cloud ), NLP ...",I am currently transitioning from project-base...

In [36]:
new_data.loc["Tarek Amr Mostafa"]

Timestamp                                                                                       2026-04-08 19:03:59.348000
Phone Number ( must have WhatsApp )                                                                            01129886261
Email                                                                                                tarekamr737@gmail.com
Please Select Preferred Scholarship type                                                                            Online
LinkedIn                                                                 https://www.linkedin.com/in/tarek-amr737?utm_s...
Please upload your CV                                                    https://drive.google.com/open?id=14KwYu3eZFsBu...
Why do you want this Scholarship?                                        As a senior AI Engineering student, this schol...
Why should we accept you?                                                You should accept me because I have a solid AI...
Where did you hear about us?                                                                                      LinkedIn
Preferred Sessions Time                                                                                              Night
What are the topics that you want to learn during this scholarship ?     MLOps ( using AWS and/or Huwawie Cloud ), NLP ...
Any notes                                                                I am highly motivated to expand my expertise i...
Name: Tarek Amr Mostafa, dtype: object

In [37]:
data

,Timestamp,Name,Phone Number ( must have WhatsApp ),Email,Please Select Preferred Scholarship type,LinkedIn,Please upload your CV,Why do you want this Scholarship?,Why should we accept you?,Where did you hear about us?,Preferred Sessions Time,What are the topics that you want to learn during this scholarship ?,Any notes
0,2026-01-23 17:25:09.672,Abdelrahman Khalil Ali Mohamed,01111070574,kabdelrahman213@gmail.com,Online,https://www.linkedin.com/in/abdelrahman-khalil...,https://drive.google.com/open?id=1OXEUPDVvHFER...,It will help me to get job,..,Facebook,Any time is ok,"Python Basics, Mathematics, Data Preprocessing...",..
1,2026-01-23 17:28:36.010,Samy Haliem,01227531720,samy.scomi@gmail.com,Online,https://www.linkedin.com/in/samyhaliem/,https://drive.google.com/open?id=1MA5qC-xYVIQl...,Carrier change,Because i love to learn,Facebook,Night,"Data Preprocessing, Data Analysis ( using pyth...",No thanks
2,2026-01-23 17:28:36.188,Rehab Abuelhassan Mohamed,01064713782,rehababuelhassan6@gmail.com,Online,www.linkedin.com/in/rehab-abuelhassan-21973b21...,https://drive.google.com/open?id=10apviXBsA4_G...,to learn,because I have some experience,Facebook,Night,"Python Basics, Mathematics, Data Preprocessing...",no
3,2026-01-23 17:30:02.485,ايات محمد فخرى محمد,01095103433,Ayatfakhary4@gmail.com,Hybrid,https://www.linkedin.com/in/ayat-fakhary-614ab...,https://drive.google.com/open?id=1SfFCARr254f_...,علشان حابة اتعلم كل مجال ال ai وكل المجالات ال...,Because I want to learn and I love this track ...,Facebook,Any time is ok,"MLOps ( using AWS and/or Huwawie Cloud ), NLP ...",حابة استفيد من المنحة واتعلم التراكات دى لان و...
4,2026-01-23 17:30:23.532,Abdelghany Ahmed Elshershapy,01552256981,abdelghany662002@gmail.com,Hybrid,https://www.linkedin.com/in/abdelghany-elshers...,https://drive.google.com/open?id=1PMchgyyWjbK0...,Because I want to land on a new job on AI fiel...,As I am self studied person who want to improv...,AItronix (currently student with them),Any time is ok,Introduction to Data Engineering ( Theoratical...,Thanks for this opportunity and I hope to be o...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
412,2026-04-02 05:35:08.338,yousef mohammed abdelkareem,01123277241,ym9159303@gmail.com,Offline,https://www.linkedin.com/in/joox/,https://drive.google.com/open?id=1Se11E-QMzEsz...,I'm a Computer Science student at Helwan Unive...,I'm not starting from zero — I already have pr...,aitronix round4,Any time is ok,"Machine Learning, Deep Learning, MLOps ( using...",naaaa
413,2026-04-06 05:32:48.638,Abdullah Abdelhakeem Sabrah,01008995928,abdosabrah49@gmail.com,Online,linkedin.com/in/abdullah-abdelhakeem-sabrah-b2...,https://drive.google.com/open?id=1TLjHveMSCeds...,"I service had ended at military, i am searchin...",I think that what i have now so i will do my b...,Linkedin,Night,Introduction to Data Engineering ( Theoratical...,Thanks
414,2026-04-08 19:03:59.348,Tarek Amr Mostafa,01129886261,tarekamr737@gmail.com,Online,https://www.linkedin.com/in/tarek-amr737?utm_s...,https://drive.google.com/open?id=14KwYu3eZFsBu...,"As a senior AI Engineering student, this schol...",You should accept me because I have a solid AI...,LinkedIn,Night,"MLOps ( using AWS and/or Huwawie Cloud ), NLP ...",I am highly motivated to expand my expertise i...
415,2026-04-11 21:53:29.407,Mohamed Amir Abouzaid Ahmed,01013390569,mohamedamirezz05@gmail.com,Online,https://www.linkedin.com/in/mohamed-amir-55727...,https://drive.google.com/open?id=1eMIahbsGNFwh...,My goal is to learn and apply my knowledge to ...,I am passionate about learning and delving dee...,Facebook,Morning,"Data Preprocessing, Introduction to Data Engin...",Please indicate if the dates are subject to ch...
416,2026-04-14 18:15:15.363,Rama Abdelgadir Imam MohamedAhmed,01123240218,Ramaabdelgadir@gmail.com,Hybrid,Linkedin.com/in/rama-abdelgadir,https://drive.google.com/open?id=1WIOGEnQRli6z...,I want to strengthen my foundation in Artifici...,I have a strong background in AI with hands-on...,Linkedin,Any time is ok,"MLOps ( using AWS and/or Huwawie Cloud ), NLP ...",I am currently transitioning from project-base...

In [41]:
data.rename({ "Phone Number ( must have WhatsApp ) ":  "phone_number" }, axis= 1 , inplace = True )

In [42]:
data

,Timestamp,Name,phone_number,Email,Please Select Preferred Scholarship type,LinkedIn,Please upload your CV,Why do you want this Scholarship?,Why should we accept you?,Where did you hear about us?,Preferred Sessions Time,What are the topics that you want to learn during this scholarship ?,Any notes
0,2026-01-23 17:25:09.672,Abdelrahman Khalil Ali Mohamed,01111070574,kabdelrahman213@gmail.com,Online,https://www.linkedin.com/in/abdelrahman-khalil...,https://drive.google.com/open?id=1OXEUPDVvHFER...,It will help me to get job,..,Facebook,Any time is ok,"Python Basics, Mathematics, Data Preprocessing...",..
1,2026-01-23 17:28:36.010,Samy Haliem,01227531720,samy.scomi@gmail.com,Online,https://www.linkedin.com/in/samyhaliem/,https://drive.google.com/open?id=1MA5qC-xYVIQl...,Carrier change,Because i love to learn,Facebook,Night,"Data Preprocessing, Data Analysis ( using pyth...",No thanks
2,2026-01-23 17:28:36.188,Rehab Abuelhassan Mohamed,01064713782,rehababuelhassan6@gmail.com,Online,www.linkedin.com/in/rehab-abuelhassan-21973b21...,https://drive.google.com/open?id=10apviXBsA4_G...,to learn,because I have some experience,Facebook,Night,"Python Basics, Mathematics, Data Preprocessing...",no
3,2026-01-23 17:30:02.485,ايات محمد فخرى محمد,01095103433,Ayatfakhary4@gmail.com,Hybrid,https://www.linkedin.com/in/ayat-fakhary-614ab...,https://drive.google.com/open?id=1SfFCARr254f_...,علشان حابة اتعلم كل مجال ال ai وكل المجالات ال...,Because I want to learn and I love this track ...,Facebook,Any time is ok,"MLOps ( using AWS and/or Huwawie Cloud ), NLP ...",حابة استفيد من المنحة واتعلم التراكات دى لان و...
4,2026-01-23 17:30:23.532,Abdelghany Ahmed Elshershapy,01552256981,abdelghany662002@gmail.com,Hybrid,https://www.linkedin.com/in/abdelghany-elshers...,https://drive.google.com/open?id=1PMchgyyWjbK0...,Because I want to land on a new job on AI fiel...,As I am self studied person who want to improv...,AItronix (currently student with them),Any time is ok,Introduction to Data Engineering ( Theoratical...,Thanks for this opportunity and I hope to be o...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
412,2026-04-02 05:35:08.338,yousef mohammed abdelkareem,01123277241,ym9159303@gmail.com,Offline,https://www.linkedin.com/in/joox/,https://drive.google.com/open?id=1Se11E-QMzEsz...,I'm a Computer Science student at Helwan Unive...,I'm not starting from zero — I already have pr...,aitronix round4,Any time is ok,"Machine Learning, Deep Learning, MLOps ( using...",naaaa
413,2026-04-06 05:32:48.638,Abdullah Abdelhakeem Sabrah,01008995928,abdosabrah49@gmail.com,Online,linkedin.com/in/abdullah-abdelhakeem-sabrah-b2...,https://drive.google.com/open?id=1TLjHveMSCeds...,"I service had ended at military, i am searchin...",I think that what i have now so i will do my b...,Linkedin,Night,Introduction to Data Engineering ( Theoratical...,Thanks
414,2026-04-08 19:03:59.348,Tarek Amr Mostafa,01129886261,tarekamr737@gmail.com,Online,https://www.linkedin.com/in/tarek-amr737?utm_s...,https://drive.google.com/open?id=14KwYu3eZFsBu...,"As a senior AI Engineering student, this schol...",You should accept me because I have a solid AI...,LinkedIn,Night,"MLOps ( using AWS and/or Huwawie Cloud ), NLP ...",I am highly motivated to expand my expertise i...
415,2026-04-11 21:53:29.407,Mohamed Amir Abouzaid Ahmed,01013390569,mohamedamirezz05@gmail.com,Online,https://www.linkedin.com/in/mohamed-amir-55727...,https://drive.google.com/open?id=1eMIahbsGNFwh...,My goal is to learn and apply my knowledge to ...,I am passionate about learning and delving dee...,Facebook,Morning,"Data Preprocessing, Introduction to Data Engin...",Please indicate if the dates are subject to ch...
416,2026-04-14 18:15:15.363,Rama Abdelgadir Imam MohamedAhmed,01123240218,Ramaabdelgadir@gmail.com,Hybrid,Linkedin.com/in/rama-abdelgadir,https://drive.google.com/open?id=1WIOGEnQRli6z...,I want to strengthen my foundation in Artifici...,I have a strong background in AI with hands-on...,Linkedin,Any time is ok,"MLOps ( using AWS and/or Huwawie Cloud ), NLP ...",I am currently transitioning from project-base...

In [49]:
for number in data.phone_number: 
    if len(str(number)) != 11 and (str(number))[0:3] != "+201" : 
        print(number)

1148660852
1270700864
1093600303
+201090020472
+201006546843
+213 552554474
+201289455213
1126724270
1098799596
+971 502530068
1111803830
011-55-099-245
1069066892
1017281928
+201156554473
+201113416111
+213 558 912 231
011 48660852
0109 965 4032
1273931608
+12169714139
+9647756004313
0109 685 2923
+201019822648
00213778663706
+201064368781
1270700864
1148660852
+201009714915
+201001902838
+201095610131
+201001376153
+201040287163

In [56]:
email_pattern = r'[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'

# Filter the DataFrame to keep only valid emails
valid_df = data[data['Email'].str.contains(email_pattern, na=False, regex=True)]

In [57]:
valid_df

,Timestamp,Name,phone_number,Email,Please Select Preferred Scholarship type,LinkedIn,Please upload your CV,Why do you want this Scholarship?,Why should we accept you?,Where did you hear about us?,Preferred Sessions Time,What are the topics that you want to learn during this scholarship ?,Any notes
0,2026-01-23 17:25:09.672,Abdelrahman Khalil Ali Mohamed,01111070574,kabdelrahman213@gmail.com,Online,https://www.linkedin.com/in/abdelrahman-khalil...,https://drive.google.com/open?id=1OXEUPDVvHFER...,It will help me to get job,..,Facebook,Any time is ok,"Python Basics, Mathematics, Data Preprocessing...",..
1,2026-01-23 17:28:36.010,Samy Haliem,01227531720,samy.scomi@gmail.com,Online,https://www.linkedin.com/in/samyhaliem/,https://drive.google.com/open?id=1MA5qC-xYVIQl...,Carrier change,Because i love to learn,Facebook,Night,"Data Preprocessing, Data Analysis ( using pyth...",No thanks
2,2026-01-23 17:28:36.188,Rehab Abuelhassan Mohamed,01064713782,rehababuelhassan6@gmail.com,Online,www.linkedin.com/in/rehab-abuelhassan-21973b21...,https://drive.google.com/open?id=10apviXBsA4_G...,to learn,because I have some experience,Facebook,Night,"Python Basics, Mathematics, Data Preprocessing...",no
3,2026-01-23 17:30:02.485,ايات محمد فخرى محمد,01095103433,Ayatfakhary4@gmail.com,Hybrid,https://www.linkedin.com/in/ayat-fakhary-614ab...,https://drive.google.com/open?id=1SfFCARr254f_...,علشان حابة اتعلم كل مجال ال ai وكل المجالات ال...,Because I want to learn and I love this track ...,Facebook,Any time is ok,"MLOps ( using AWS and/or Huwawie Cloud ), NLP ...",حابة استفيد من المنحة واتعلم التراكات دى لان و...
4,2026-01-23 17:30:23.532,Abdelghany Ahmed Elshershapy,01552256981,abdelghany662002@gmail.com,Hybrid,https://www.linkedin.com/in/abdelghany-elshers...,https://drive.google.com/open?id=1PMchgyyWjbK0...,Because I want to land on a new job on AI fiel...,As I am self studied person who want to improv...,AItronix (currently student with them),Any time is ok,Introduction to Data Engineering ( Theoratical...,Thanks for this opportunity and I hope to be o...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
412,2026-04-02 05:35:08.338,yousef mohammed abdelkareem,01123277241,ym9159303@gmail.com,Offline,https://www.linkedin.com/in/joox/,https://drive.google.com/open?id=1Se11E-QMzEsz...,I'm a Computer Science student at Helwan Unive...,I'm not starting from zero — I already have pr...,aitronix round4,Any time is ok,"Machine Learning, Deep Learning, MLOps ( using...",naaaa
413,2026-04-06 05:32:48.638,Abdullah Abdelhakeem Sabrah,01008995928,abdosabrah49@gmail.com,Online,linkedin.com/in/abdullah-abdelhakeem-sabrah-b2...,https://drive.google.com/open?id=1TLjHveMSCeds...,"I service had ended at military, i am searchin...",I think that what i have now so i will do my b...,Linkedin,Night,Introduction to Data Engineering ( Theoratical...,Thanks
414,2026-04-08 19:03:59.348,Tarek Amr Mostafa,01129886261,tarekamr737@gmail.com,Online,https://www.linkedin.com/in/tarek-amr737?utm_s...,https://drive.google.com/open?id=14KwYu3eZFsBu...,"As a senior AI Engineering student, this schol...",You should accept me because I have a solid AI...,LinkedIn,Night,"MLOps ( using AWS and/or Huwawie Cloud ), NLP ...",I am highly motivated to expand my expertise i...
415,2026-04-11 21:53:29.407,Mohamed Amir Abouzaid Ahmed,01013390569,mohamedamirezz05@gmail.com,Online,https://www.linkedin.com/in/mohamed-amir-55727...,https://drive.google.com/open?id=1eMIahbsGNFwh...,My goal is to learn and apply my knowledge to ...,I am passionate about learning and delving dee...,Facebook,Morning,"Data Preprocessing, Introduction to Data Engin...",Please indicate if the dates are subject to ch...
416,2026-04-14 18:15:15.363,Rama Abdelgadir Imam MohamedAhmed,01123240218,Ramaabdelgadir@gmail.com,Hybrid,Linkedin.com/in/rama-abdelgadir,https://drive.google.com/open?id=1WIOGEnQRli6z...,I want to strengthen my foundation in Artifici...,I have a strong background in AI with hands-on...,Linkedin,Any time is ok,"MLOps ( using AWS and/or Huwawie Cloud ), NLP ...",I am currently transitioning from project-base...

In [58]:
invalied_emails = data[~(data['Email'].str.contains(email_pattern, na=False, regex=True))]
invalied_emails

,Timestamp,Name,phone_number,Email,Please Select Preferred Scholarship type,LinkedIn,Please upload your CV,Why do you want this Scholarship?,Why should we accept you?,Where did you hear about us?,Preferred Sessions Time,What are the topics that you want to learn during this scholarship ?,Any notes
80,2026-01-23 23:58:52.392,محمد طارق توفيق,01278418942,mozatarek200@gmail.com,Online,https://www.linkedin.com/in/mohamed-tarek-997a...,https://drive.google.com/open?id=1GnTTBTvp1CxR...,انا داتا انالسيز وعايز اطور من نفسى اكتر واتعل...,عندي معرفه ودرايه بالمجال متعلم الاساسيات واشت...,فيسبوك,Night,"Mathematics, Introduction to Data Engineering ...",شكرا جدا على المنحة
84,2026-01-24 00:18:28.355,Mustafa Ahmed Abbas,1098799596,eng.mustafaahmed10@gmail.com,Online,https://www.linkedin.com/in/mustafa-ahmed-9935...,https://drive.google.com/open?id=1yktgTSvuMjJ0...,I am seeking this scholarship because it will ...,You should accept me because I combine strong ...,Facebook,Night,"Python Basics, Mathematics, Data Preprocessing...",Thanks
91,2026-01-24 02:07:00.213,Alaa Mahmoud Elkewisny,+971 502530068,alaaelkewisny@gmail.com,Online,www.linkedin.com/in/alaa-elkewisny-1542a933b,https://drive.google.com/open?id=1s42QiePw7WK2...,This scholarship provides me the opportunity t...,You should accept me because I already have a ...,LinkedIn,Any time is ok,All AI Topics,Nothing
104,2026-01-24 11:07:35.981,Mariam Ashraf Megahed,1111803830,Myinventionfuture@gmail.com,Hybrid,https://www.linkedin.com/in/mariam-ashraf-0aba...,https://drive.google.com/open?id=1RnM5pnNVDIZO...,To learn ai,I am passionate in this field,LinkedIn,Night,"Machine Learning, Deep Learning, NLP & LLMs, C...",No
143,2026-01-25 08:10:12.785,Mohamed badran,01004914060,Eng.mohamedbadran@gmail.com,Online,https://www.linkedin.com/in/muhamedbadran,https://drive.google.com/open?id=1jRlQK5gDNuE9...,I am passionate about mastering Artificial Int...,You should accept me because:\n\n1. Demonstrat...,LinkedIn,Night,"Mathematics, Data Preprocessing, Data Analysis...",I am genuinely enthusiastic about joining this...
188,2026-01-28 15:29:15.047,rahma hassaan abdelkader,01147840216,rahmahassaan75@gmail.com,Hybrid,www.linkedin.com/in/rahma-hassaan👑-3703142ab,https://drive.google.com/open?id=1yXMtcYRi22wr...,I want this scholarship to become a skilled AI...,You should accept me because I am a motivated ...,from LinkedIn,Night,"Machine Learning, Deep Learning, MLOps ( using...","no,thanks"
202,2026-01-29 16:54:41.431,Ehdaa Abdalluh Mohamed Abdullah,1273931608,ehdaaabdalla0@gmail.com,Hybrid,https://www.linkedin.com/in/ehdaa-abdalla-a542...,https://drive.google.com/open?id=1SAIi4rz3MBMC...,Because I study communication and electronics ...,Because I understand quickly and I am committe...,LinkedIn,Any time is ok,"Python Basics, Mathematics, Data Preprocessing...",No
259,2026-02-05 13:43:38.733,Mariam Mansour Albasyouni,01008918158,mariam.mansour1752@gmail.com,Online,NaN,https://drive.google.com/open?id=1EtBESQkGtdLc...,"""I am driven to pursue this scholarship becaus...",You should accept me because I combine a solid...,Social media,Night,"Mathematics, Deep Learning, Computer Vision, A...",..
260,2026-02-05 13:47:29.638,Mariam Mansour Albasyouni,01008918158,mariam.mansour1752@gmail.com,Online,NaN,https://drive.google.com/open?id=1ENXzj0ULz_xY...,"""I am driven to pursue this scholarship becaus...",You should accept me because I combine a solid...,Social media,Night,"Mathematics, Deep Learning, Agentic AI, AI Too...",..
295,2026-02-11 16:53:34.530,Mariam Hany,1270700864,Mariamhanybt18@gmail.com,Hybrid,https://www.linkedin.com/in/mariam-hany-715b89...,https://drive.google.com/open?id=1-G1RfkJsFv5Z...,Because I want to develop myself more to get t...,I want to benefit from you as much as I can an...,From my friends,Morning,"Python Basics, Mathematics, Data Preprocessing...",I hope to get the most benefit from this schol...
296,2026-02-11 17:24:06.872,Roqaia Hany Mohammed Ragab,01067469939,rokiaragab29@gmail.com‏,Online,https://www.linkedin.com/in/roqaia-ragab-b9b39...,https://drive.google.com/open?id=1BeAHGdY2vSOQ...,I want this scholarship because it will help m...,"You should accept me because I am dedicated, h...",Facebook,Night,"Data Preprocessing, Data Analysis ( using pyth...",No
307,2026-02-11 20:33:47.648,Eman Yasser Elnaggar,01025106441,emanelnaggar.2019@gmail.com,Online,https://www.linkedin.com/in/eman-elnaggar-6529...,https://drive.google.com/open?id=1P4K0bZueyntu...,I am interested in the grant because of the te...,I have a little experience as I have had some ...,LinkedIn,Night,"MLOps ( using AWS and/or Huwawie Cloud ), NLP ...",No thanks
329,2026-02-12 11:51:30.339,Morad askar hassan elnahla,01024011971,moradelnahla@gmail.com‏,Online,https://www.linkedin.com/in/morad-elnahla?utm_...,https://drive.google.com/open?id=10zPenIXAl6Ev...,I want this scholarship to deepen my knowledge...,I am motivated and disciplined . I have a soli...,recommendations from friends,After Noon,"Data Analysis ( using python ), Machine Learni...",No thanks
359,2026-02-15 09:15:36.529,Omar Hussein Ahmed,01019733887,Omar.hussein.cs.2025@gmail.com,Hybrid,https://www.linkedin.com/in/omar-hussein-ahmed...,https://drive.google.com/open?id=1eupmcH75IOQ6...,Because this is my field of study and the futu...,Because I am hardworking and committed.,LinkedIn,Night,"Machine Learning, Deep Learning, MLOps ( using...",On thanks
371,2026-02-17 23:17:34.973,Abdulrahman Sayed,01120824518,abdelrahmansayed01120824518@gmail.com‏,Online,https://www.linkedin.com/in/abdulrahman-sayed-...,https://drive.google.com/open?id=13jYCgCVWXFQ7...,to improve my skills,will be happy and study hard,LinkedIn,Night,All AI Topics,thanks

In [62]:
valid_df = data[~(data['Email'].str.contains(email_pattern, na=False, regex=True) )]

In [64]:
valid_df.shape

(15, 13)

In [65]:
valid_df

,Timestamp,Name,phone_number,Email,Please Select Preferred Scholarship type,LinkedIn,Please upload your CV,Why do you want this Scholarship?,Why should we accept you?,Where did you hear about us?,Preferred Sessions Time,What are the topics that you want to learn during this scholarship ?,Any notes
80,2026-01-23 23:58:52.392,محمد طارق توفيق,01278418942,mozatarek200@gmail.com,Online,https://www.linkedin.com/in/mohamed-tarek-997a...,https://drive.google.com/open?id=1GnTTBTvp1CxR...,انا داتا انالسيز وعايز اطور من نفسى اكتر واتعل...,عندي معرفه ودرايه بالمجال متعلم الاساسيات واشت...,فيسبوك,Night,"Mathematics, Introduction to Data Engineering ...",شكرا جدا على المنحة
84,2026-01-24 00:18:28.355,Mustafa Ahmed Abbas,1098799596,eng.mustafaahmed10@gmail.com,Online,https://www.linkedin.com/in/mustafa-ahmed-9935...,https://drive.google.com/open?id=1yktgTSvuMjJ0...,I am seeking this scholarship because it will ...,You should accept me because I combine strong ...,Facebook,Night,"Python Basics, Mathematics, Data Preprocessing...",Thanks
91,2026-01-24 02:07:00.213,Alaa Mahmoud Elkewisny,+971 502530068,alaaelkewisny@gmail.com,Online,www.linkedin.com/in/alaa-elkewisny-1542a933b,https://drive.google.com/open?id=1s42QiePw7WK2...,This scholarship provides me the opportunity t...,You should accept me because I already have a ...,LinkedIn,Any time is ok,All AI Topics,Nothing
104,2026-01-24 11:07:35.981,Mariam Ashraf Megahed,1111803830,Myinventionfuture@gmail.com,Hybrid,https://www.linkedin.com/in/mariam-ashraf-0aba...,https://drive.google.com/open?id=1RnM5pnNVDIZO...,To learn ai,I am passionate in this field,LinkedIn,Night,"Machine Learning, Deep Learning, NLP & LLMs, C...",No
143,2026-01-25 08:10:12.785,Mohamed badran,01004914060,Eng.mohamedbadran@gmail.com,Online,https://www.linkedin.com/in/muhamedbadran,https://drive.google.com/open?id=1jRlQK5gDNuE9...,I am passionate about mastering Artificial Int...,You should accept me because:\n\n1. Demonstrat...,LinkedIn,Night,"Mathematics, Data Preprocessing, Data Analysis...",I am genuinely enthusiastic about joining this...
188,2026-01-28 15:29:15.047,rahma hassaan abdelkader,01147840216,rahmahassaan75@gmail.com,Hybrid,www.linkedin.com/in/rahma-hassaan👑-3703142ab,https://drive.google.com/open?id=1yXMtcYRi22wr...,I want this scholarship to become a skilled AI...,You should accept me because I am a motivated ...,from LinkedIn,Night,"Machine Learning, Deep Learning, MLOps ( using...","no,thanks"
202,2026-01-29 16:54:41.431,Ehdaa Abdalluh Mohamed Abdullah,1273931608,ehdaaabdalla0@gmail.com,Hybrid,https://www.linkedin.com/in/ehdaa-abdalla-a542...,https://drive.google.com/open?id=1SAIi4rz3MBMC...,Because I study communication and electronics ...,Because I understand quickly and I am committe...,LinkedIn,Any time is ok,"Python Basics, Mathematics, Data Preprocessing...",No
259,2026-02-05 13:43:38.733,Mariam Mansour Albasyouni,01008918158,mariam.mansour1752@gmail.com,Online,NaN,https://drive.google.com/open?id=1EtBESQkGtdLc...,"""I am driven to pursue this scholarship becaus...",You should accept me because I combine a solid...,Social media,Night,"Mathematics, Deep Learning, Computer Vision, A...",..
260,2026-02-05 13:47:29.638,Mariam Mansour Albasyouni,01008918158,mariam.mansour1752@gmail.com,Online,NaN,https://drive.google.com/open?id=1ENXzj0ULz_xY...,"""I am driven to pursue this scholarship becaus...",You should accept me because I combine a solid...,Social media,Night,"Mathematics, Deep Learning, Agentic AI, AI Too...",..
295,2026-02-11 16:53:34.530,Mariam Hany,1270700864,Mariamhanybt18@gmail.com,Hybrid,https://www.linkedin.com/in/mariam-hany-715b89...,https://drive.google.com/open?id=1-G1RfkJsFv5Z...,Because I want to develop myself more to get t...,I want to benefit from you as much as I can an...,From my friends,Morning,"Python Basics, Mathematics, Data Preprocessing...",I hope to get the most benefit from this schol...
296,2026-02-11 17:24:06.872,Roqaia Hany Mohammed Ragab,01067469939,rokiaragab29@gmail.com‏,Online,https://www.linkedin.com/in/roqaia-ragab-b9b39...,https://drive.google.com/open?id=1BeAHGdY2vSOQ...,I want this scholarship because it will help m...,"You should accept me because I am dedicated, h...",Facebook,Night,"Data Preprocessing, Data Analysis ( using pyth...",No
307,2026-02-11 20:33:47.648,Eman Yasser Elnaggar,01025106441,emanelnaggar.2019@gmail.com,Online,https://www.linkedin.com/in/eman-elnaggar-6529...,https://drive.google.com/open?id=1P4K0bZueyntu...,I am interested in the grant because of the te...,I have a little experience as I have had some ...,LinkedIn,Night,"MLOps ( using AWS and/or Huwawie Cloud ), NLP ...",No thanks
329,2026-02-12 11:51:30.339,Morad askar hassan elnahla,01024011971,moradelnahla@gmail.com‏,Online,https://www.linkedin.com/in/morad-elnahla?utm_...,https://drive.google.com/open?id=10zPenIXAl6Ev...,I want this scholarship to deepen my knowledge...,I am motivated and disciplined . I have a soli...,recommendations from friends,After Noon,"Data Analysis ( using python ), Machine Learni...",No thanks
359,2026-02-15 09:15:36.529,Omar Hussein Ahmed,01019733887,Omar.hussein.cs.2025@gmail.com,Hybrid,https://www.linkedin.com/in/omar-hussein-ahmed...,https://drive.google.com/open?id=1eupmcH75IOQ6...,Because this is my field of study and the futu...,Because I am hardworking and committed.,LinkedIn,Night,"Machine Learning, Deep Learning, MLOps ( using...",On thanks
371,2026-02-17 23:17:34.973,Abdulrahman Sayed,01120824518,abdelrahmansayed01120824518@gmail.com‏,Online,https://www.linkedin.com/in/abdulrahman-sayed-...,https://drive.google.com/open?id=13jYCgCVWXFQ7...,to improve my skills,will be happy and study hard,LinkedIn,Night,All AI Topics,thanks

In [71]:
counter = 0 
for email in data.Email : 
    if email.split("@")[1].strip() != "gmail.com": 
        print(email.split("@"))
        counter += 1

counter

['m.samir2264', 'nu.edu.eg']
['nada.bastawi', 'ejust.edu.eg']
['mohamedalihassan26', 'outlook.com']
['Saharamrahmed', 'gmail.con']
['rahmahassaan75', 'gmai.com']
['mathewemad', 'aol.com']
['hagar_1219a', 'eng.kfs.edu.eg']
['224254', 'eru.edu.eg']
['mahmoudalashry1', 'outlook.com']
['Yousef.Ibrahim.2230238', 'CIT.hnu.edu.eg']
['Daarsh2003', 'msn.com']
['ak2158', 'fayoum.edu.eg']
['R2DY2005', 'GMAIL.COM']
['rokiaragab29', 'gmail.com\u200f']
['yomnasoror220', 'gimal.com']
['moradelnahla', 'gmail.com\u200f']
['202303039', 'pua.edu.eg']
['abdelrahmansayed01120824518', 'gmail.com\u200f']
['moustafaserag', 'yahoo.com']

19

In [73]:
data["Please Select Preferred Scholarship type "].value_counts()

Please Select Preferred Scholarship type
Online     214
Hybrid     152
Offline     51
Name: count, dtype: int64

In [74]:
data

,Timestamp,Name,phone_number,Email,Please Select Preferred Scholarship type,LinkedIn,Please upload your CV,Why do you want this Scholarship?,Why should we accept you?,Where did you hear about us?,Preferred Sessions Time,What are the topics that you want to learn during this scholarship ?,Any notes
0,2026-01-23 17:25:09.672,Abdelrahman Khalil Ali Mohamed,01111070574,kabdelrahman213@gmail.com,Online,https://www.linkedin.com/in/abdelrahman-khalil...,https://drive.google.com/open?id=1OXEUPDVvHFER...,It will help me to get job,..,Facebook,Any time is ok,"Python Basics, Mathematics, Data Preprocessing...",..
1,2026-01-23 17:28:36.010,Samy Haliem,01227531720,samy.scomi@gmail.com,Online,https://www.linkedin.com/in/samyhaliem/,https://drive.google.com/open?id=1MA5qC-xYVIQl...,Carrier change,Because i love to learn,Facebook,Night,"Data Preprocessing, Data Analysis ( using pyth...",No thanks
2,2026-01-23 17:28:36.188,Rehab Abuelhassan Mohamed,01064713782,rehababuelhassan6@gmail.com,Online,www.linkedin.com/in/rehab-abuelhassan-21973b21...,https://drive.google.com/open?id=10apviXBsA4_G...,to learn,because I have some experience,Facebook,Night,"Python Basics, Mathematics, Data Preprocessing...",no
3,2026-01-23 17:30:02.485,ايات محمد فخرى محمد,01095103433,Ayatfakhary4@gmail.com,Hybrid,https://www.linkedin.com/in/ayat-fakhary-614ab...,https://drive.google.com/open?id=1SfFCARr254f_...,علشان حابة اتعلم كل مجال ال ai وكل المجالات ال...,Because I want to learn and I love this track ...,Facebook,Any time is ok,"MLOps ( using AWS and/or Huwawie Cloud ), NLP ...",حابة استفيد من المنحة واتعلم التراكات دى لان و...
4,2026-01-23 17:30:23.532,Abdelghany Ahmed Elshershapy,01552256981,abdelghany662002@gmail.com,Hybrid,https://www.linkedin.com/in/abdelghany-elshers...,https://drive.google.com/open?id=1PMchgyyWjbK0...,Because I want to land on a new job on AI fiel...,As I am self studied person who want to improv...,AItronix (currently student with them),Any time is ok,Introduction to Data Engineering ( Theoratical...,Thanks for this opportunity and I hope to be o...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
412,2026-04-02 05:35:08.338,yousef mohammed abdelkareem,01123277241,ym9159303@gmail.com,Offline,https://www.linkedin.com/in/joox/,https://drive.google.com/open?id=1Se11E-QMzEsz...,I'm a Computer Science student at Helwan Unive...,I'm not starting from zero — I already have pr...,aitronix round4,Any time is ok,"Machine Learning, Deep Learning, MLOps ( using...",naaaa
413,2026-04-06 05:32:48.638,Abdullah Abdelhakeem Sabrah,01008995928,abdosabrah49@gmail.com,Online,linkedin.com/in/abdullah-abdelhakeem-sabrah-b2...,https://drive.google.com/open?id=1TLjHveMSCeds...,"I service had ended at military, i am searchin...",I think that what i have now so i will do my b...,Linkedin,Night,Introduction to Data Engineering ( Theoratical...,Thanks
414,2026-04-08 19:03:59.348,Tarek Amr Mostafa,01129886261,tarekamr737@gmail.com,Online,https://www.linkedin.com/in/tarek-amr737?utm_s...,https://drive.google.com/open?id=14KwYu3eZFsBu...,"As a senior AI Engineering student, this schol...",You should accept me because I have a solid AI...,LinkedIn,Night,"MLOps ( using AWS and/or Huwawie Cloud ), NLP ...",I am highly motivated to expand my expertise i...
415,2026-04-11 21:53:29.407,Mohamed Amir Abouzaid Ahmed,01013390569,mohamedamirezz05@gmail.com,Online,https://www.linkedin.com/in/mohamed-amir-55727...,https://drive.google.com/open?id=1eMIahbsGNFwh...,My goal is to learn and apply my knowledge to ...,I am passionate about learning and delving dee...,Facebook,Morning,"Data Preprocessing, Introduction to Data Engin...",Please indicate if the dates are subject to ch...
416,2026-04-14 18:15:15.363,Rama Abdelgadir Imam MohamedAhmed,01123240218,Ramaabdelgadir@gmail.com,Hybrid,Linkedin.com/in/rama-abdelgadir,https://drive.google.com/open?id=1WIOGEnQRli6z...,I want to strengthen my foundation in Artifici...,I have a strong background in AI with hands-on...,Linkedin,Any time is ok,"MLOps ( using AWS and/or Huwawie Cloud ), NLP ...",I am currently transitioning from project-base...

In [75]:
data["Why do you want this Scholarship?"].nunique()

412

In [76]:
data["Where did you hear about us?"].nunique()

189

In [77]:
data["Where did you hear about us?"]

0                                   Facebook
1                                    Facebook
2                                   Facebook
3                                   Facebook
4      AItronix (currently student with them)
                        ...
412                          aitronix round4
413                                  Linkedin
414                                  LinkedIn
415                                 Facebook
416                                 Linkedin
Name: Where did you hear about us?, Length: 417, dtype: str

In [79]:
data["Preferred Sessions Time"].value_counts()

Preferred Sessions Time
Night             196
Any time is ok    127
Morning            47
After Noon         47
Name: count, dtype: int64

In [82]:
data.rename({
    "What are the topics that you want to learn during this scholarship ? " : "topic"
}, axis = 1 , inplace= True )

In [83]:
data

,Timestamp,Name,phone_number,Email,Please Select Preferred Scholarship type,LinkedIn,Please upload your CV,Why do you want this Scholarship?,Why should we accept you?,Where did you hear about us?,Preferred Sessions Time,topic,Any notes
0,2026-01-23 17:25:09.672,Abdelrahman Khalil Ali Mohamed,01111070574,kabdelrahman213@gmail.com,Online,https://www.linkedin.com/in/abdelrahman-khalil...,https://drive.google.com/open?id=1OXEUPDVvHFER...,It will help me to get job,..,Facebook,Any time is ok,"Python Basics, Mathematics, Data Preprocessing...",..
1,2026-01-23 17:28:36.010,Samy Haliem,01227531720,samy.scomi@gmail.com,Online,https://www.linkedin.com/in/samyhaliem/,https://drive.google.com/open?id=1MA5qC-xYVIQl...,Carrier change,Because i love to learn,Facebook,Night,"Data Preprocessing, Data Analysis ( using pyth...",No thanks
2,2026-01-23 17:28:36.188,Rehab Abuelhassan Mohamed,01064713782,rehababuelhassan6@gmail.com,Online,www.linkedin.com/in/rehab-abuelhassan-21973b21...,https://drive.google.com/open?id=10apviXBsA4_G...,to learn,because I have some experience,Facebook,Night,"Python Basics, Mathematics, Data Preprocessing...",no
3,2026-01-23 17:30:02.485,ايات محمد فخرى محمد,01095103433,Ayatfakhary4@gmail.com,Hybrid,https://www.linkedin.com/in/ayat-fakhary-614ab...,https://drive.google.com/open?id=1SfFCARr254f_...,علشان حابة اتعلم كل مجال ال ai وكل المجالات ال...,Because I want to learn and I love this track ...,Facebook,Any time is ok,"MLOps ( using AWS and/or Huwawie Cloud ), NLP ...",حابة استفيد من المنحة واتعلم التراكات دى لان و...
4,2026-01-23 17:30:23.532,Abdelghany Ahmed Elshershapy,01552256981,abdelghany662002@gmail.com,Hybrid,https://www.linkedin.com/in/abdelghany-elshers...,https://drive.google.com/open?id=1PMchgyyWjbK0...,Because I want to land on a new job on AI fiel...,As I am self studied person who want to improv...,AItronix (currently student with them),Any time is ok,Introduction to Data Engineering ( Theoratical...,Thanks for this opportunity and I hope to be o...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
412,2026-04-02 05:35:08.338,yousef mohammed abdelkareem,01123277241,ym9159303@gmail.com,Offline,https://www.linkedin.com/in/joox/,https://drive.google.com/open?id=1Se11E-QMzEsz...,I'm a Computer Science student at Helwan Unive...,I'm not starting from zero — I already have pr...,aitronix round4,Any time is ok,"Machine Learning, Deep Learning, MLOps ( using...",naaaa
413,2026-04-06 05:32:48.638,Abdullah Abdelhakeem Sabrah,01008995928,abdosabrah49@gmail.com,Online,linkedin.com/in/abdullah-abdelhakeem-sabrah-b2...,https://drive.google.com/open?id=1TLjHveMSCeds...,"I service had ended at military, i am searchin...",I think that what i have now so i will do my b...,Linkedin,Night,Introduction to Data Engineering ( Theoratical...,Thanks
414,2026-04-08 19:03:59.348,Tarek Amr Mostafa,01129886261,tarekamr737@gmail.com,Online,https://www.linkedin.com/in/tarek-amr737?utm_s...,https://drive.google.com/open?id=14KwYu3eZFsBu...,"As a senior AI Engineering student, this schol...",You should accept me because I have a solid AI...,LinkedIn,Night,"MLOps ( using AWS and/or Huwawie Cloud ), NLP ...",I am highly motivated to expand my expertise i...
415,2026-04-11 21:53:29.407,Mohamed Amir Abouzaid Ahmed,01013390569,mohamedamirezz05@gmail.com,Online,https://www.linkedin.com/in/mohamed-amir-55727...,https://drive.google.com/open?id=1eMIahbsGNFwh...,My goal is to learn and apply my knowledge to ...,I am passionate about learning and delving dee...,Facebook,Morning,"Data Preprocessing, Introduction to Data Engin...",Please indicate if the dates are subject to ch...
416,2026-04-14 18:15:15.363,Rama Abdelgadir Imam MohamedAhmed,01123240218,Ramaabdelgadir@gmail.com,Hybrid,Linkedin.com/in/rama-abdelgadir,https://drive.google.com/open?id=1WIOGEnQRli6z...,I want to strengthen my foundation in Artifici...,I have a strong background in AI with hands-on...,Linkedin,Any time is ok,"MLOps ( using AWS and/or Huwawie Cloud ), NLP ...",I am currently transitioning from project-base...

In [84]:
data.topic

0      Python Basics, Mathematics, Data Preprocessing...
1      Data Preprocessing, Data Analysis ( using pyth...
2      Python Basics, Mathematics, Data Preprocessing...
3      MLOps ( using AWS and/or Huwawie Cloud ), NLP ...
4      Introduction to Data Engineering ( Theoratical...
                             ...
412    Machine Learning, Deep Learning, MLOps ( using...
413    Introduction to Data Engineering ( Theoratical...
414    MLOps ( using AWS and/or Huwawie Cloud ), NLP ...
415    Data Preprocessing, Introduction to Data Engin...
416    MLOps ( using AWS and/or Huwawie Cloud ), NLP ...
Name: topic, Length: 417, dtype: str

In [86]:
data.topic.str.split(",").explode().value_counts()

topic
 NLP & LLMs                                          281
 Agentic AI                                          278
 AI Tools                                            263
 Deep Learning                                       256
 Computer Vision                                     246
 MLOps ( using AWS and/or Huwawie Cloud )            240
 Machine Learning                                    224
 All AI Topics                                       199
 Data Analysis ( using python )                      174
 Introduction to Data Engineering ( Theoratical )    157
 Data Preprocessing                                  156
Python Basics                                        136
 Mathematics                                         113
All AI Topics                                         53
Mathematics                                           50
Machine Learning                                      38
Introduction to Data Engineering ( Theoratical )      28
Data Preprocessing                                    27
MLOps ( using AWS and/or Huwawie Cloud )              27
Deep Learning                                         24
Data Analysis ( using python )                        23
NLP & LLMs                                             7
Agentic AI                                             3
AI Tools                                               1
Name: count, dtype: int64

In [89]:
data.topic[0]

'Python Basics, Mathematics, Data Preprocessing, Data Analysis ( using python ), Introduction to Data Engineering ( Theoratical ), Machine Learning, Deep Learning, NLP & LLMs, AI Tools, All AI Topics'

In [90]:
data["topic"] = data.topic.str.replace(" ", ""  )

In [91]:
data["topic"]

0      PythonBasics,Mathematics,DataPreprocessing,Dat...
1      DataPreprocessing,DataAnalysis(usingpython),Ma...
2      PythonBasics,Mathematics,DataPreprocessing,Dat...
3      MLOps(usingAWSand/orHuwawieCloud),NLP&LLMs,Com...
4      IntroductiontoDataEngineering(Theoratical),Mac...
                             ...
412    MachineLearning,DeepLearning,MLOps(usingAWSand...
413    IntroductiontoDataEngineering(Theoratical),MLO...
414    MLOps(usingAWSand/orHuwawieCloud),NLP&LLMs,Com...
415    DataPreprocessing,IntroductiontoDataEngineerin...
416    MLOps(usingAWSand/orHuwawieCloud),NLP&LLMs,Age...
Name: topic, Length: 417, dtype: str

In [92]:
data.topic.str.split(",").explode().value_counts()

topic
NLP&LLMs                                      288
AgenticAI                                     281
DeepLearning                                  280
MLOps(usingAWSand/orHuwawieCloud)             267
AITools                                       264
MachineLearning                               262
AllAITopics                                   252
ComputerVision                                246
DataAnalysis(usingpython)                     197
IntroductiontoDataEngineering(Theoratical)    185
DataPreprocessing                             183
Mathematics                                   163
PythonBasics                                  136
Name: count, dtype: int64

In [93]:
for t in data.topic : 
    topics = t.split(",")
    if "AllAITopics" in topics and len(topics) > 1 :
        print(topics )

['PythonBasics', 'Mathematics', 'DataPreprocessing', 'DataAnalysis(usingpython)', 'IntroductiontoDataEngineering(Theoratical)', 'MachineLearning', 'DeepLearning', 'NLP&LLMs', 'AITools', 'AllAITopics']
['DataPreprocessing', 'DataAnalysis(usingpython)', 'MachineLearning', 'DeepLearning', 'AllAITopics']
['DeepLearning', 'MLOps(usingAWSand/orHuwawieCloud)', 'NLP&LLMs', 'ComputerVision', 'AllAITopics']
['Mathematics', 'DataPreprocessing', 'DataAnalysis(usingpython)', 'IntroductiontoDataEngineering(Theoratical)', 'MachineLearning', 'DeepLearning', 'MLOps(usingAWSand/orHuwawieCloud)', 'NLP&LLMs', 'ComputerVision', 'AgenticAI', 'AITools', 'AllAITopics']
['IntroductiontoDataEngineering(Theoratical)', 'MachineLearning', 'DeepLearning', 'MLOps(usingAWSand/orHuwawieCloud)', 'NLP&LLMs', 'AgenticAI', 'AITools', 'AllAITopics']
['PythonBasics', 'Mathematics', 'DataPreprocessing', 'DataAnalysis(usingpython)', 'IntroductiontoDataEngineering(Theoratical)', 'MachineLearning', 'DeepLearning', 'MLOps(usingAWSand/orHuwawieCloud)', 'NLP&LLMs', 'ComputerVision', 'AgenticAI', 'AITools', 'AllAITopics']
['PythonBasics', 'DataPreprocessing', 'DataAnalysis(usingpython)', 'MachineLearning', 'DeepLearning', 'NLP&LLMs', 'AllAITopics']
['DeepLearning', 'MLOps(usingAWSand/orHuwawieCloud)', 'NLP&LLMs', 'ComputerVision', 'AgenticAI', 'AITools', 'AllAITopics']
['IntroductiontoDataEngineering(Theoratical)', 'MachineLearning', 'DeepLearning', 'MLOps(usingAWSand/orHuwawieCloud)', 'NLP&LLMs', 'ComputerVision', 'AgenticAI', 'AITools', 'AllAITopics']
['PythonBasics', 'Mathematics', 'DataPreprocessing', 'DataAnalysis(usingpython)', 'IntroductiontoDataEngineering(Theoratical)', 'MachineLearning', 'DeepLearning', 'MLOps(usingAWSand/orHuwawieCloud)', 'NLP&LLMs', 'ComputerVision', 'AgenticAI', 'AITools', 'AllAITopics']
['PythonBasics', 'Mathematics', 'DataPreprocessing', 'DataAnalysis(usingpython)', 'IntroductiontoDataEngineering(Theoratical)', 'MachineLearning', 'MLOps(usingAWSand/orHuwawieCloud)', 'AllAITopics']
['PythonBasics', 'DataPreprocessing', 'DataAnalysis(usingpython)', 'IntroductiontoDataEngineering(Theoratical)', 'MachineLearning', 'DeepLearning', 'MLOps(usingAWSand/orHuwawieCloud)', 'NLP&LLMs', 'ComputerVision', 'AgenticAI', 'AITools', 'AllAITopics']
['MachineLearning', 'DeepLearning', 'MLOps(usingAWSand/orHuwawieCloud)', 'NLP&LLMs', 'ComputerVision', 'AgenticAI', 'AllAITopics']
['PythonBasics', 'Mathematics', 'DataPreprocessing', 'DataAnalysis(usingpython)', 'IntroductiontoDataEngineering(Theoratical)', 'MachineLearning', 'DeepLearning', 'MLOps(usingAWSand/orHuwawieCloud)', 'NLP&LLMs', 'ComputerVision', 'AgenticAI', 'AITools', 'AllAITopics']
['PythonBasics', 'Mathematics', 'DataPreprocessing', 'DataAnalysis(usingpython)', 'IntroductiontoDataEngineering(Theoratical)', 'MachineLearning', 'DeepLearning', 'MLOps(usingAWSand/orHuwawieCloud)', 'NLP&LLMs', 'ComputerVision', 'AgenticAI', 'AITools', 'AllAITopics']
['Mathematics', 'DataPreprocessing', 'DataAnalysis(usingpython)', 'MachineLearning', 'DeepLearning', 'MLOps(usingAWSand/orHuwawieCloud)', 'NLP&LLMs', 'AllAITopics']
['PythonBasics', 'Mathematics', 'DataPreprocessing', 'DataAnalysis(usingpython)', 'IntroductiontoDataEngineering(Theoratical)', 'MachineLearning', 'DeepLearning', 'MLOps(usingAWSand/orHuwawieCloud)', 'NLP&LLMs', 'ComputerVision', 'AgenticAI', 'AITools', 'AllAITopics']
['PythonBasics', 'Mathematics', 'DataPreprocessing', 'DataAnalysis(usingpython)', 'IntroductiontoDataEngineering(Theoratical)', 'MachineLearning', 'DeepLearning', 'NLP&LLMs', 'ComputerVision', 'AgenticAI', 'AITools', 'AllAITopics']
['Mathematics', 'DataPreprocessing', 'DataAnalysis(usingpython)', 'IntroductiontoDataEngineering(Theoratical)', 'MachineLearning', 'DeepLearning', 'MLOps(usingAWSand/orHuwawieCloud)', 'NLP&LLMs', 'ComputerVision', 'AgenticAI', 'AITools', 'AllAITopics']
['Mathematics', 'DataPreprocessing', 'DataAnalysis(usingpython)', 'IntroductiontoDataEngineering(Theoratical)', 'MachineLearning', 'DeepLearning', 'MLOps(usingAWSand/orHuwawieCloud)', 'NLP&LLMs', 'ComputerVision', 'AgenticAI', 'AITools', 'AllAITopics']
['PythonBasics', 'Mathematics', 'DataPreprocessing', 'DataAnalysis(usingpython)', 'IntroductiontoDataEngineering(Theoratical)', 'MachineLearning', 'DeepLearning', 'MLOps(usingAWSand/orHuwawieCloud)', 'NLP&LLMs', 'ComputerVision', 'AgenticAI', 'AITools', 'AllAITopics']
['MachineLearning', 'DeepLearning', 'MLOps(usingAWSand/orHuwawieCloud)', 'NLP&LLMs', 'ComputerVision', 'AgenticAI', 'AITools', 'AllAITopics']
['PythonBasics', 'Mathematics', 'DataPreprocessing', 'DataAnalysis(usingpython)', 'IntroductiontoDataEngineering(Theoratical)', 'MachineLearning', 'DeepLearning', 'MLOps(usingAWSand/orHuwawieCloud)', 'NLP&LLMs', 'ComputerVision', 'AgenticAI', 'AITools', 'AllAITopics']
['PythonBasics', 'Mathematics', 'DataPreprocessing', 'DataAnalysis(usingpython)', 'IntroductiontoDataEngineering(Theoratical)', 'MachineLearning', 'DeepLearning', 'MLOps(usingAWSand/orHuwawieCloud)', 'NLP&LLMs', 'ComputerVision', 'AgenticAI', 'AITools', 'AllAITopics']
['PythonBasics', 'Mathematics', 'DataPreprocessing', 'DataAnalysis(usingpython)', 'MachineLearning', 'DeepLearning', 'NLP&LLMs', 'ComputerVision', 'AgenticAI', 'AITools', 'AllAITopics']
['PythonBasics', 'Mathematics', 'DataPreprocessing', 'DataAnalysis(usingpython)', 'IntroductiontoDataEngineering(Theoratical)', 'MachineLearning', 'DeepLearning', 'MLOps(usingAWSand/orHuwawieCloud)', 'NLP&LLMs', 'ComputerVision', 'AgenticAI', 'AITools', 'AllAITopics']
['PythonBasics', 'Mathematics', 'DataPreprocessing', 'DataAnalysis(usingpython)', 'IntroductiontoDataEngineering(Theoratical)', 'MachineLearning', 'DeepLearning', 'MLOps(usingAWSand/orHuwawieCloud)', 'NLP&LLMs', 'ComputerVision', 'AgenticAI', 'AITools', 'AllAITopics']
['IntroductiontoDataEngineering(Theoratical)', 'MLOps(usingAWSand/orHuwawieCloud)', 'NLP&LLMs', 'ComputerVision', 'AgenticAI', 'AITools', 'AllAITopics']
['Mathematics', 'DataPreprocessing', 'DataAnalysis(usingpython)', 'IntroductiontoDataEngineering(Theoratical)', 'MachineLearning', 'DeepLearning', 'MLOps(usingAWSand/orHuwawieCloud)', 'NLP&LLMs', 'ComputerVision', 'AgenticAI', 'AITools', 'AllAITopics']
['Mathematics', 'MLOps(usingAWSand/orHuwawieCloud)', 'NLP&LLMs', 'ComputerVision', 'AgenticAI', 'AllAITopics']
['DataPreprocessing', 'DataAnalysis(usingpython)', 'MachineLearning', 'DeepLearning', 'AgenticAI', 'AITools', 'AllAITopics']
['PythonBasics', 'Mathematics', 'DataPreprocessing', 'DataAnalysis(usingpython)', 'IntroductiontoDataEngineering(Theoratical)', 'MachineLearning', 'DeepLearning', 'MLOps(usingAWSand/orHuwawieCloud)', 'NLP&LLMs', 'ComputerVision', 'AgenticAI', 'AITools', 'AllAITopics']
['PythonBasics', 'Mathematics', 'DataPreprocessing', 'DataAnalysis(usingpython)', 'IntroductiontoDataEngineering(Theoratical)', 'MachineLearning', 'DeepLearning', 'MLOps(usingAWSand/orHuwawieCloud)', 'NLP&LLMs', 'ComputerVision', 'AgenticAI', 'AITools', 'AllAITopics']
['Mathematics', 'DataPreprocessing', 'DataAnalysis(usingpython)', 'MachineLearning', 'DeepLearning', 'MLOps(usingAWSand/orHuwawieCloud)', 'NLP&LLMs', 'AgenticAI', 'AITools', 'AllAITopics']
['Mathematics', 'MachineLearning', 'DeepLearning', 'MLOps(usingAWSand/orHuwawieCloud)', 'NLP&LLMs', 'ComputerVision', 'AgenticAI', 'AITools', 'AllAITopics']
['IntroductiontoDataEngineering(Theoratical)', 'MachineLearning', 'DeepLearning', 'MLOps(usingAWSand/orHuwawieCloud)', 'NLP&LLMs', 'ComputerVision', 'AgenticAI', 'AITools', 'AllAITopics']
['PythonBasics', 'Mathematics', 'DataPreprocessing', 'DataAnalysis(usingpython)', 'IntroductiontoDataEngineering(Theoratical)', 'MachineLearning', 'AITools', 'AllAITopics']
['PythonBasics', 'Mathematics', 'DataPreprocessing', 'DataAnalysis(usingpython)', 'IntroductiontoDataEngineering(Theoratical)', 'MachineLearning', 'DeepLearning', 'MLOps(usingAWSand/orHuwawieCloud)', 'NLP&LLMs', 'ComputerVision', 'AgenticAI', 'AITools', 'AllAITopics']
['PythonBasics', 'Mathematics', 'DataPreprocessing', 'DataAnalysis(usingpython)', 'IntroductiontoDataEngineering(Theoratical)', 'MachineLearning', 'DeepLearning', 'MLOps(usingAWSand/orHuwawieCloud)', 'NLP&LLMs', 'ComputerVision', 'AgenticAI', 'AITools', 'AllAITopics']
['PythonBasics', 'Mathematics', 'DataPreprocessing', 'DataAnalysis(usingpython)', 'IntroductiontoDataEngineering(Theoratical)', 'MachineLearning', 'DeepLearning', 'MLOps(usingAWSand/orHuwawieCloud)', 'NLP&LLMs', 'ComputerVision', 'AgenticAI', 'AITools', 'AllAITopics']
['PythonBasics', 'Mathematics', 'DataPreprocessing', 'DataAnalysis(usingpython)', 'IntroductiontoDataEngineering(Theoratical)', 'MachineLearning', 'DeepLearning', 'MLOps(usingAWSand/orHuwawieCloud)', 'NLP&LLMs', 'ComputerVision', 'AgenticAI', 'AITools', 'AllAITopics']
['DataPreprocessing', 'DataAnalysis(usingpython)', 'DeepLearning', 'NLP&LLMs', 'ComputerVision', 'AgenticAI', 'AllAITopics']
['PythonBasics', 'Mathematics', 'DataPreprocessing', 'DataAnalysis(usingpython)', 'IntroductiontoDataEngineering(Theoratical)', 'MachineLearning', 'DeepLearning', 'MLOps(usingAWSand/orHuwawieCloud)', 'NLP&LLMs', 'ComputerVision', 'AgenticAI', 'AITools', 'AllAITopics']
['Mathematics', 'IntroductiontoDataEngineering(Theoratical)', 'MachineLearning', 'DeepLearning', 'MLOps(usingAWSand/orHuwawieCloud)', 'NLP&LLMs', 'ComputerVision', 'AgenticAI', 'AITools', 'AllAITopics']
['PythonBasics', 'Mathematics', 'DataPreprocessing', 'DataAnalysis(usingpython)', 'IntroductiontoDataEngineering(Theoratical)', 'MachineLearning', 'NLP&LLMs', 'AllAITopics']
['PythonBasics', 'Mathematics', 'DataPreprocessing', 'IntroductiontoDataEngineering(Theoratical)', 'MachineLearning', 'DeepLearning', 'MLOps(usingAWSand/orHuwawieCloud)', 'NLP&LLMs', 'ComputerVision', 'AgenticAI', 'AITools', 'AllAITopics']
['PythonBasics', 'MachineLearning', 'DeepLearning', 'MLOps(usingAWSand/orHuwawieCloud)', 'NLP&LLMs', 'AgenticAI', 'AITools', 'AllAITopics']
['PythonBasics', 'Mathematics', 'IntroductiontoDataEngineering(Theoratical)', 'MachineLearning', 'DeepLearning', 'MLOps(usingAWSand/orHuwawieCloud)', 'NLP&LLMs', 'ComputerVision', 'AgenticAI', 'AITools', 'AllAITopics']
['PythonBasics', 'Mathematics', 'DataPreprocessing', 'DataAnalysis(usingpython)', 'IntroductiontoDataEngineering(Theoratical)', 'MachineLearning', 'DeepLearning', 'MLOps(usingAWSand/orHuwawieCloud)', 'NLP&LLMs', 'ComputerVision', 'AgenticAI', 'AITools', 'AllAITopics']
['PythonBasics', 'Mathematics', 'DataPreprocessing', 'DataAnalysis(usingpython)', 'IntroductiontoDataEngineering(Theoratical)', 'MachineLearning', 'DeepLearning', 'MLOps(usingAWSand/orHuwawieCloud)', 'NLP&LLMs', 'ComputerVision', 'AgenticAI', 'AITools', 'AllAITopics']
['Mathematics', 'MachineLearning', 'DeepLearning', 'MLOps(usingAWSand/orHuwawieCloud)', 'NLP&LLMs', 'ComputerVision', 'AgenticAI', 'AITools', 'AllAITopics']
['PythonBasics', 'DataPreprocessing', 'DataAnalysis(usingpython)', 'MachineLearning', 'DeepLearning', 'AgenticAI', 'AITools', 'AllAITopics']
['PythonBasics', 'Mathematics', 'DataPreprocessing', 'DataAnalysis(usingpython)', 'IntroductiontoDataEngineering(Theoratical)', 'MachineLearning', 'DeepLearning', 'MLOps(usingAWSand/orHuwawieCloud)', 'NLP&LLMs', 'ComputerVision', 'AgenticAI', 'AITools', 'AllAITopics']
['PythonBasics', 'Mathematics', 'DataPreprocessing', 'DataAnalysis(usingpython)', 'IntroductiontoDataEngineering(Theoratical)', 'MachineLearning', 'DeepLearning', 'MLOps(usingAWSand/orHuwawieCloud)', 'NLP&LLMs', 'ComputerVision', 'AgenticAI', 'AITools', 'AllAITopics']
['DataAnalysis(usingpython)', 'MachineLearning', 'DeepLearning', 'AgenticAI', 'AITools', 'AllAITopics']
['PythonBasics', 'Mathematics', 'DataPreprocessing', 'DataAnalysis(usingpython)', 'IntroductiontoDataEngineering(Theoratical)', 'MachineLearning', 'DeepLearning', 'MLOps(usingAWSand/orHuwawieCloud)', 'NLP&LLMs', 'ComputerVision', 'AgenticAI', 'AITools', 'AllAITopics']
['PythonBasics', 'Mathematics', 'DataPreprocessing', 'DataAnalysis(usingpython)', 'IntroductiontoDataEngineering(Theoratical)', 'MachineLearning', 'DeepLearning', 'MLOps(usingAWSand/orHuwawieCloud)', 'NLP&LLMs', 'ComputerVision', 'AgenticAI', 'AITools', 'AllAITopics']
['DeepLearning', 'MLOps(usingAWSand/orHuwawieCloud)', 'NLP&LLMs', 'ComputerVision', 'AgenticAI', 'AITools', 'AllAITopics']
['IntroductiontoDataEngineering(Theoratical)', 'DeepLearning', 'MLOps(usingAWSand/orHuwawieCloud)', 'NLP&LLMs', 'AgenticAI', 'AITools', 'AllAITopics']
['PythonBasics', 'DataAnalysis(usingpython)', 'IntroductiontoDataEngineering(Theoratical)', 'MachineLearning', 'MLOps(usingAWSand/orHuwawieCloud)', 'AllAITopics']
['PythonBasics', 'AITools', 'AllAITopics']
['IntroductiontoDataEngineering(Theoratical)', 'MachineLearning', 'DeepLearning', 'MLOps(usingAWSand/orHuwawieCloud)', 'NLP&LLMs', 'AgenticAI', 'AITools', 'AllAITopics']
['PythonBasics', 'MachineLearning', 'DeepLearning', 'AgenticAI', 'AITools', 'AllAITopics']
['Mathematics', 'DataPreprocessing', 'IntroductiontoDataEngineering(Theoratical)', 'MachineLearning', 'DeepLearning', 'MLOps(usingAWSand/orHuwawieCloud)', 'NLP&LLMs', 'ComputerVision', 'AgenticAI', 'AITools', 'AllAITopics']
['DataPreprocessing', 'DataAnalysis(usingpython)', 'IntroductiontoDataEngineering(Theoratical)', 'MachineLearning', 'DeepLearning', 'MLOps(usingAWSand/orHuwawieCloud)', 'NLP&LLMs', 'ComputerVision', 'AgenticAI', 'AITools', 'AllAITopics']
['DataAnalysis(usingpython)', 'IntroductiontoDataEngineering(Theoratical)', 'DeepLearning', 'MLOps(usingAWSand/orHuwawieCloud)', 'NLP&LLMs', 'AgenticAI', 'AITools', 'AllAITopics']
['IntroductiontoDataEngineering(Theoratical)', 'AllAITopics']
['PythonBasics', 'Mathematics', 'DataPreprocessing', 'DataAnalysis(usingpython)', 'IntroductiontoDataEngineering(Theoratical)', 'MachineLearning', 'DeepLearning', 'MLOps(usingAWSand/orHuwawieCloud)', 'NLP&LLMs', 'ComputerVision', 'AgenticAI', 'AITools', 'AllAITopics']
['PythonBasics', 'Mathematics', 'DataPreprocessing', 'DataAnalysis(usingpython)', 'IntroductiontoDataEngineering(Theoratical)', 'MachineLearning', 'DeepLearning', 'MLOps(usingAWSand/orHuwawieCloud)', 'NLP&LLMs', 'ComputerVision', 'AgenticAI', 'AITools', 'AllAITopics']
['PythonBasics', 'Mathematics', 'DataPreprocessing', 'DataAnalysis(usingpython)', 'IntroductiontoDataEngineering(Theoratical)', 'MachineLearning', 'DeepLearning', 'MLOps(usingAWSand/orHuwawieCloud)', 'NLP&LLMs', 'ComputerVision', 'AgenticAI', 'AITools', 'AllAITopics']
['DeepLearning', 'MLOps(usingAWSand/orHuwawieCloud)', 'NLP&LLMs', 'ComputerVision', 'AgenticAI', 'AITools', 'AllAITopics']
['PythonBasics', 'Mathematics', 'DataPreprocessing', 'DataAnalysis(usingpython)', 'IntroductiontoDataEngineering(Theoratical)', 'MachineLearning', 'DeepLearning', 'MLOps(usingAWSand/orHuwawieCloud)', 'NLP&LLMs', 'ComputerVision', 'AgenticAI', 'AITools', 'AllAITopics']
['PythonBasics', 'Mathematics', 'DataPreprocessing', 'DataAnalysis(usingpython)', 'IntroductiontoDataEngineering(Theoratical)', 'MachineLearning', 'DeepLearning', 'MLOps(usingAWSand/orHuwawieCloud)', 'NLP&LLMs', 'ComputerVision', 'AgenticAI', 'AITools', 'AllAITopics']
['MLOps(usingAWSand/orHuwawieCloud)', 'NLP&LLMs', 'AITools', 'AllAITopics']
['MachineLearning', 'DeepLearning', 'MLOps(usingAWSand/orHuwawieCloud)', 'NLP&LLMs', 'ComputerVision', 'AgenticAI', 'AITools', 'AllAITopics']
['MachineLearning', 'DeepLearning', 'MLOps(usingAWSand/orHuwawieCloud)', 'NLP&LLMs', 'ComputerVision', 'AgenticAI', 'AITools', 'AllAITopics']
['DataAnalysis(usingpython)', 'MachineLearning', 'DeepLearning', 'MLOps(usingAWSand/orHuwawieCloud)', 'NLP&LLMs', 'ComputerVision', 'AgenticAI', 'AITools', 'AllAITopics']
['Mathematics', 'DataPreprocessing', 'DataAnalysis(usingpython)', 'IntroductiontoDataEngineering(Theoratical)', 'MachineLearning', 'DeepLearning', 'NLP&LLMs', 'ComputerVision', 'AgenticAI', 'AITools', 'AllAITopics']
['Mathematics', 'DataPreprocessing', 'DataAnalysis(usingpython)', 'IntroductiontoDataEngineering(Theoratical)', 'MachineLearning', 'DeepLearning', 'MLOps(usingAWSand/orHuwawieCloud)', 'NLP&LLMs', 'ComputerVision', 'AgenticAI', 'AITools', 'AllAITopics']
['DataAnalysis(usingpython)', 'MachineLearning', 'DeepLearning', 'NLP&LLMs', 'ComputerVision', 'AllAITopics']
['MachineLearning', 'DeepLearning', 'NLP&LLMs', 'ComputerVision', 'AllAITopics']
['PythonBasics', 'Mathematics', 'DataPreprocessing', 'DataAnalysis(usingpython)', 'IntroductiontoDataEngineering(Theoratical)', 'MachineLearning', 'DeepLearning', 'MLOps(usingAWSand/orHuwawieCloud)', 'NLP&LLMs', 'ComputerVision', 'AgenticAI', 'AITools', 'AllAITopics']
['MLOps(usingAWSand/orHuwawieCloud)', 'NLP&LLMs', 'AgenticAI', 'AllAITopics']
['MachineLearning', 'MLOps(usingAWSand/orHuwawieCloud)', 'AllAITopics']
['PythonBasics', 'Mathematics', 'DataPreprocessing', 'DataAnalysis(usingpython)', 'IntroductiontoDataEngineering(Theoratical)', 'MachineLearning', 'DeepLearning', 'MLOps(usingAWSand/orHuwawieCloud)', 'NLP&LLMs', 'ComputerVision', 'AgenticAI', 'AITools', 'AllAITopics']
['PythonBasics', 'Mathematics', 'DataPreprocessing', 'DataAnalysis(usingpython)', 'IntroductiontoDataEngineering(Theoratical)', 'MachineLearning', 'DeepLearning', 'MLOps(usingAWSand/orHuwawieCloud)', 'NLP&LLMs', 'ComputerVision', 'AgenticAI', 'AITools', 'AllAITopics']
['PythonBasics', 'Mathematics', 'DataPreprocessing', 'DataAnalysis(usingpython)', 'IntroductiontoDataEngineering(Theoratical)', 'MachineLearning', 'DeepLearning', 'MLOps(usingAWSand/orHuwawieCloud)', 'NLP&LLMs', 'ComputerVision', 'AgenticAI', 'AITools', 'AllAITopics']
['PythonBasics', 'DataPreprocessing', 'DataAnalysis(usingpython)', 'IntroductiontoDataEngineering(Theoratical)', 'MachineLearning', 'DeepLearning', 'MLOps(usingAWSand/orHuwawieCloud)', 'AITools', 'AllAITopics']
['IntroductiontoDataEngineering(Theoratical)', 'MachineLearning', 'DeepLearning', 'MLOps(usingAWSand/orHuwawieCloud)', 'NLP&LLMs', 'AgenticAI', 'AITools', 'AllAITopics']
['PythonBasics', 'Mathematics', 'DataPreprocessing', 'DataAnalysis(usingpython)', 'IntroductiontoDataEngineering(Theoratical)', 'MachineLearning', 'DeepLearning', 'MLOps(usingAWSand/orHuwawieCloud)', 'NLP&LLMs', 'ComputerVision', 'AgenticAI', 'AITools', 'AllAITopics']
['Mathematics', 'DataAnalysis(usingpython)', 'IntroductiontoDataEngineering(Theoratical)', 'DeepLearning', 'MLOps(usingAWSand/orHuwawieCloud)', 'AgenticAI', 'AllAITopics']
['DataPreprocessing', 'DataAnalysis(usingpython)', 'IntroductiontoDataEngineering(Theoratical)', 'MachineLearning', 'DeepLearning', 'MLOps(usingAWSand/orHuwawieCloud)', 'NLP&LLMs', 'ComputerVision', 'AgenticAI', 'AITools', 'AllAITopics']
['MachineLearning', 'DeepLearning', 'MLOps(usingAWSand/orHuwawieCloud)', 'NLP&LLMs', 'ComputerVision', 'AgenticAI', 'AITools', 'AllAITopics']
['MLOps(usingAWSand/orHuwawieCloud)', 'NLP&LLMs', 'ComputerVision', 'AgenticAI', 'AITools', 'AllAITopics']
['PythonBasics', 'Mathematics', 'DataPreprocessing', 'DataAnalysis(usingpython)', 'DeepLearning', 'NLP&LLMs', 'ComputerVision', 'AgenticAI', 'AITools', 'AllAITopics']
['PythonBasics', 'Mathematics', 'DataPreprocessing', 'DataAnalysis(usingpython)', 'IntroductiontoDataEngineering(Theoratical)', 'MachineLearning', 'DeepLearning', 'MLOps(usingAWSand/orHuwawieCloud)', 'NLP&LLMs', 'ComputerVision', 'AgenticAI', 'AITools', 'AllAITopics']
['Mathematics', 'DataPreprocessing', 'DataAnalysis(usingpython)', 'IntroductiontoDataEngineering(Theoratical)', 'MachineLearning', 'DeepLearning', 'MLOps(usingAWSand/orHuwawieCloud)', 'NLP&LLMs', 'ComputerVision', 'AgenticAI', 'AITools', 'AllAITopics']
['PythonBasics', 'Mathematics', 'DataPreprocessing', 'DataAnalysis(usingpython)', 'IntroductiontoDataEngineering(Theoratical)', 'MachineLearning', 'DeepLearning', 'MLOps(usingAWSand/orHuwawieCloud)', 'NLP&LLMs', 'ComputerVision', 'AgenticAI', 'AITools', 'AllAITopics']
['PythonBasics', 'Mathematics', 'DataPreprocessing', 'DataAnalysis(usingpython)', 'IntroductiontoDataEngineering(Theoratical)', 'MachineLearning', 'DeepLearning', 'MLOps(usingAWSand/orHuwawieCloud)', 'NLP&LLMs', 'ComputerVision', 'AgenticAI', 'AITools', 'AllAITopics']

In [94]:
for t in data.topic : 
    topics = t.split(",")
    if "AllAITopics" in topics and len(topics) ==1 :
        print(topics )

['AllAITopics']
['AllAITopics']
['AllAITopics']
['AllAITopics']
['AllAITopics']
['AllAITopics']
['AllAITopics']
['AllAITopics']
['AllAITopics']
['AllAITopics']
['AllAITopics']
['AllAITopics']
['AllAITopics']
['AllAITopics']
['AllAITopics']
['AllAITopics']
['AllAITopics']
['AllAITopics']
['AllAITopics']
['AllAITopics']
['AllAITopics']
['AllAITopics']
['AllAITopics']
['AllAITopics']
['AllAITopics']
['AllAITopics']
['AllAITopics']
['AllAITopics']
['AllAITopics']
['AllAITopics']
['AllAITopics']
['AllAITopics']
['AllAITopics']
['AllAITopics']
['AllAITopics']
['AllAITopics']
['AllAITopics']
['AllAITopics']
['AllAITopics']
['AllAITopics']
['AllAITopics']
['AllAITopics']
['AllAITopics']
['AllAITopics']
['AllAITopics']
['AllAITopics']
['AllAITopics']
['AllAITopics']
['AllAITopics']
['AllAITopics']
['AllAITopics']
['AllAITopics']
['AllAITopics']

In [95]:
data["topic"] = data.topic.str.contains("AllAITopics").replace("AllAITopics")

ValueError: Series.replace must specify either 'value', a dict-like 'to_replace', or dict-like 'regex'.

In [97]:
import numpy as np

In [98]:
data["topic"] = np.where(data["topic"].str.contains("AllAITopics", na=False), "AllAITopics", data["topic"])

In [99]:
data

,Timestamp,Name,phone_number,Email,Please Select Preferred Scholarship type,LinkedIn,Please upload your CV,Why do you want this Scholarship?,Why should we accept you?,Where did you hear about us?,Preferred Sessions Time,topic,Any notes
0,2026-01-23 17:25:09.672,Abdelrahman Khalil Ali Mohamed,01111070574,kabdelrahman213@gmail.com,Online,https://www.linkedin.com/in/abdelrahman-khalil...,https://drive.google.com/open?id=1OXEUPDVvHFER...,It will help me to get job,..,Facebook,Any time is ok,AllAITopics,..
1,2026-01-23 17:28:36.010,Samy Haliem,01227531720,samy.scomi@gmail.com,Online,https://www.linkedin.com/in/samyhaliem/,https://drive.google.com/open?id=1MA5qC-xYVIQl...,Carrier change,Because i love to learn,Facebook,Night,AllAITopics,No thanks
2,2026-01-23 17:28:36.188,Rehab Abuelhassan Mohamed,01064713782,rehababuelhassan6@gmail.com,Online,www.linkedin.com/in/rehab-abuelhassan-21973b21...,https://drive.google.com/open?id=10apviXBsA4_G...,to learn,because I have some experience,Facebook,Night,"PythonBasics,Mathematics,DataPreprocessing,Dat...",no
3,2026-01-23 17:30:02.485,ايات محمد فخرى محمد,01095103433,Ayatfakhary4@gmail.com,Hybrid,https://www.linkedin.com/in/ayat-fakhary-614ab...,https://drive.google.com/open?id=1SfFCARr254f_...,علشان حابة اتعلم كل مجال ال ai وكل المجالات ال...,Because I want to learn and I love this track ...,Facebook,Any time is ok,"MLOps(usingAWSand/orHuwawieCloud),NLP&LLMs,Com...",حابة استفيد من المنحة واتعلم التراكات دى لان و...
4,2026-01-23 17:30:23.532,Abdelghany Ahmed Elshershapy,01552256981,abdelghany662002@gmail.com,Hybrid,https://www.linkedin.com/in/abdelghany-elshers...,https://drive.google.com/open?id=1PMchgyyWjbK0...,Because I want to land on a new job on AI fiel...,As I am self studied person who want to improv...,AItronix (currently student with them),Any time is ok,"IntroductiontoDataEngineering(Theoratical),Mac...",Thanks for this opportunity and I hope to be o...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
412,2026-04-02 05:35:08.338,yousef mohammed abdelkareem,01123277241,ym9159303@gmail.com,Offline,https://www.linkedin.com/in/joox/,https://drive.google.com/open?id=1Se11E-QMzEsz...,I'm a Computer Science student at Helwan Unive...,I'm not starting from zero — I already have pr...,aitronix round4,Any time is ok,"MachineLearning,DeepLearning,MLOps(usingAWSand...",naaaa
413,2026-04-06 05:32:48.638,Abdullah Abdelhakeem Sabrah,01008995928,abdosabrah49@gmail.com,Online,linkedin.com/in/abdullah-abdelhakeem-sabrah-b2...,https://drive.google.com/open?id=1TLjHveMSCeds...,"I service had ended at military, i am searchin...",I think that what i have now so i will do my b...,Linkedin,Night,AllAITopics,Thanks
414,2026-04-08 19:03:59.348,Tarek Amr Mostafa,01129886261,tarekamr737@gmail.com,Online,https://www.linkedin.com/in/tarek-amr737?utm_s...,https://drive.google.com/open?id=14KwYu3eZFsBu...,"As a senior AI Engineering student, this schol...",You should accept me because I have a solid AI...,LinkedIn,Night,"MLOps(usingAWSand/orHuwawieCloud),NLP&LLMs,Com...",I am highly motivated to expand my expertise i...
415,2026-04-11 21:53:29.407,Mohamed Amir Abouzaid Ahmed,01013390569,mohamedamirezz05@gmail.com,Online,https://www.linkedin.com/in/mohamed-amir-55727...,https://drive.google.com/open?id=1eMIahbsGNFwh...,My goal is to learn and apply my knowledge to ...,I am passionate about learning and delving dee...,Facebook,Morning,"DataPreprocessing,IntroductiontoDataEngineerin...",Please indicate if the dates are subject to ch...
416,2026-04-14 18:15:15.363,Rama Abdelgadir Imam MohamedAhmed,01123240218,Ramaabdelgadir@gmail.com,Hybrid,Linkedin.com/in/rama-abdelgadir,https://drive.google.com/open?id=1WIOGEnQRli6z...,I want to strengthen my foundation in Artifici...,I have a strong background in AI with hands-on...,Linkedin,Any time is ok,AllAITopics,I am currently transitioning from project-base...

In [100]:
data.topic.str.split(",").explode().value_counts()

topic
AllAITopics                                   252
NLP&LLMs                                      113
AgenticAI                                     109
DeepLearning                                  104
MLOps(usingAWSand/orHuwawieCloud)              98
MachineLearning                                94
ComputerVision                                 93
AITools                                        89
DataAnalysis(usingpython)                      66
DataPreprocessing                              55
IntroductiontoDataEngineering(Theoratical)     51
Mathematics                                    43
PythonBasics                                   28
Name: count, dtype: int64

In [101]:
data["Where did you hear about us?"]

0                                   Facebook
1                                    Facebook
2                                   Facebook
3                                   Facebook
4      AItronix (currently student with them)
                        ...
412                          aitronix round4
413                                  Linkedin
414                                  LinkedIn
415                                 Facebook
416                                 Linkedin
Name: Where did you hear about us?, Length: 417, dtype: str

In [102]:
data["Where did you hear about us?"].unique()

<ArrowStringArray>
[                                                                                                                                  'Facebook ',
                                                                                                                                    'Facebook',
                                                                                                      'AItronix (currently student with them)',
                                  'I heard about Atrionix through social media, where your scholarship announcement was shared and discussed.',
                                                                  'I heard about this opportunity from a teaching assistant at my university.',
                                                                      'I Already talked with Dr. Ahmed Before at AI for X That's How It Goes ',
                                                                                                                              'Facebook page ',
                                                                                  'LinkedIn and Facebook. I follow aitronix on both platforms',
                                                                                                               'Ahmed Hafez Page on Facebook ',
                                                                                                                                   'LinkedIn ',
 ...
                                                                                                                    'A friend recommendation ',
                                                                                                                                  'Linkedin\n',
                                                                                                          'From LinkedIn profile Ahmed Hafiz ',
                                                                                                                  'I'm a student in ML course',
                                                                                                              'I'm a student in the ML course',
                                                                                                                                'Social Media',
                                                                                                                     'My Friends and LinkedIn',
                                                                                                                                 'linked in\n',
 'I heard about this scholarship from my friend Youssef Emad, who studies with me at the same faculty. He is also connected with the academy.',
                                                                                                                            'aitronix round4 ']
Length: 189, dtype: str

In [104]:
data.rename({
    "Where did you hear about us?" : "source"
} ,axis = 1, inplace= True )

In [106]:
data["source"] = data.source.str.strip().str.title()

In [107]:
data

,Timestamp,Name,phone_number,Email,Please Select Preferred Scholarship type,LinkedIn,Please upload your CV,Why do you want this Scholarship?,Why should we accept you?,source,Preferred Sessions Time,topic,Any notes
0,2026-01-23 17:25:09.672,Abdelrahman Khalil Ali Mohamed,01111070574,kabdelrahman213@gmail.com,Online,https://www.linkedin.com/in/abdelrahman-khalil...,https://drive.google.com/open?id=1OXEUPDVvHFER...,It will help me to get job,..,Facebook,Any time is ok,Allaitopics,..
1,2026-01-23 17:28:36.010,Samy Haliem,01227531720,samy.scomi@gmail.com,Online,https://www.linkedin.com/in/samyhaliem/,https://drive.google.com/open?id=1MA5qC-xYVIQl...,Carrier change,Because i love to learn,Facebook,Night,Allaitopics,No thanks
2,2026-01-23 17:28:36.188,Rehab Abuelhassan Mohamed,01064713782,rehababuelhassan6@gmail.com,Online,www.linkedin.com/in/rehab-abuelhassan-21973b21...,https://drive.google.com/open?id=10apviXBsA4_G...,to learn,because I have some experience,Facebook,Night,"Pythonbasics,Mathematics,Datapreprocessing,Dat...",no
3,2026-01-23 17:30:02.485,ايات محمد فخرى محمد,01095103433,Ayatfakhary4@gmail.com,Hybrid,https://www.linkedin.com/in/ayat-fakhary-614ab...,https://drive.google.com/open?id=1SfFCARr254f_...,علشان حابة اتعلم كل مجال ال ai وكل المجالات ال...,Because I want to learn and I love this track ...,Facebook,Any time is ok,"Mlops(Usingawsand/Orhuwawiecloud),Nlp&Llms,Com...",حابة استفيد من المنحة واتعلم التراكات دى لان و...
4,2026-01-23 17:30:23.532,Abdelghany Ahmed Elshershapy,01552256981,abdelghany662002@gmail.com,Hybrid,https://www.linkedin.com/in/abdelghany-elshers...,https://drive.google.com/open?id=1PMchgyyWjbK0...,Because I want to land on a new job on AI fiel...,As I am self studied person who want to improv...,Aitronix (Currently Student With Them),Any time is ok,"Introductiontodataengineering(Theoratical),Mac...",Thanks for this opportunity and I hope to be o...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
412,2026-04-02 05:35:08.338,yousef mohammed abdelkareem,01123277241,ym9159303@gmail.com,Offline,https://www.linkedin.com/in/joox/,https://drive.google.com/open?id=1Se11E-QMzEsz...,I'm a Computer Science student at Helwan Unive...,I'm not starting from zero — I already have pr...,Aitronix Round4,Any time is ok,"Machinelearning,Deeplearning,Mlops(Usingawsand...",naaaa
413,2026-04-06 05:32:48.638,Abdullah Abdelhakeem Sabrah,01008995928,abdosabrah49@gmail.com,Online,linkedin.com/in/abdullah-abdelhakeem-sabrah-b2...,https://drive.google.com/open?id=1TLjHveMSCeds...,"I service had ended at military, i am searchin...",I think that what i have now so i will do my b...,Linkedin,Night,Allaitopics,Thanks
414,2026-04-08 19:03:59.348,Tarek Amr Mostafa,01129886261,tarekamr737@gmail.com,Online,https://www.linkedin.com/in/tarek-amr737?utm_s...,https://drive.google.com/open?id=14KwYu3eZFsBu...,"As a senior AI Engineering student, this schol...",You should accept me because I have a solid AI...,Linkedin,Night,"Mlops(Usingawsand/Orhuwawiecloud),Nlp&Llms,Com...",I am highly motivated to expand my expertise i...
415,2026-04-11 21:53:29.407,Mohamed Amir Abouzaid Ahmed,01013390569,mohamedamirezz05@gmail.com,Online,https://www.linkedin.com/in/mohamed-amir-55727...,https://drive.google.com/open?id=1eMIahbsGNFwh...,My goal is to learn and apply my knowledge to ...,I am passionate about learning and delving dee...,Facebook,Morning,"Datapreprocessing,Introductiontodataengineerin...",Please indicate if the dates are subject to ch...
416,2026-04-14 18:15:15.363,Rama Abdelgadir Imam MohamedAhmed,01123240218,Ramaabdelgadir@gmail.com,Hybrid,Linkedin.com/in/rama-abdelgadir,https://drive.google.com/open?id=1WIOGEnQRli6z...,I want to strengthen my foundation in Artifici...,I have a strong background in AI with hands-on...,Linkedin,Any time is ok,Allaitopics,I am currently transitioning from project-base...

In [108]:
data["source"].unique()

<ArrowStringArray>
[                                                                                                                                   'Facebook',
                                                                                                      'Aitronix (Currently Student With Them)',
                                  'I Heard About Atrionix Through Social Media, Where Your Scholarship Announcement Was Shared And Discussed.',
                                                                  'I Heard About This Opportunity From A Teaching Assistant At My University.',
                                                                       'I Already Talked With Dr. Ahmed Before At Ai For X That'S How It Goes',
                                                                                                                               'Facebook Page',
                                                                                  'Linkedin And Facebook. I Follow Aitronix On Both Platforms',
                                                                                                                'Ahmed Hafez Page On Facebook',
                                                                                                                                    'Linkedin',
                                                                                                                                   'Linked-In',
 ...
                                                                                                                               'My University',
                                                                                                                               'Post Linkedin',
                                                                                                                          'Facebook, Linkedin',
                                                                                                                     'A Friend Recommendation',
                                                                                                           'From Linkedin Profile Ahmed Hafiz',
                                                                                                                  'I'M A Student In Ml Course',
                                                                                                              'I'M A Student In The Ml Course',
                                                                                                                     'My Friends And Linkedin',
 'I Heard About This Scholarship From My Friend Youssef Emad, Who Studies With Me At The Same Faculty. He Is Also Connected With The Academy.',
                                                                                                                             'Aitronix Round4']
Length: 150, dtype: str

In [109]:
data["source"].nunique()

150

In [110]:
data["source"].value_counts()

source
Linkedin                                                                                                                                       159
Facebook                                                                                                                                        50
Linked In                                                                                                                                       23
Social Media                                                                                                                                     7
From Linkedin                                                                                                                                    7
                                                                                                                                              ...
I'M A Student In Ml Course                                                                                                                       1
I'M A Student In The Ml Course                                                                                                                   1
My Friends And Linkedin                                                                                                                          1
I Heard About This Scholarship From My Friend Youssef Emad, Who Studies With Me At The Same Faculty. He Is Also Connected With The Academy.      1
Aitronix Round4                                                                                                                                  1
Name: count, Length: 150, dtype: int64

In [111]:
data [data.source.str.lower().str.contains("aitronix")]

,Timestamp,Name,phone_number,Email,Please Select Preferred Scholarship type,LinkedIn,Please upload your CV,Why do you want this Scholarship?,Why should we accept you?,source,Preferred Sessions Time,topic,Any notes
4,2026-01-23 17:30:23.532,Abdelghany Ahmed Elshershapy,01552256981,abdelghany662002@gmail.com,Hybrid,https://www.linkedin.com/in/abdelghany-elshers...,https://drive.google.com/open?id=1PMchgyyWjbK0...,Because I want to land on a new job on AI fiel...,As I am self studied person who want to improv...,Aitronix (Currently Student With Them),Any time is ok,"Introductiontodataengineering(Theoratical),Mac...",Thanks for this opportunity and I hope to be o...
10,2026-01-23 17:43:37.597,Ahmed Walid Ibrahim,01101212219,Ahmedwalidinquiries@gmail.com,Offline,https://www.linkedin.com/in/ahmed-walid-nito,https://drive.google.com/open?id=1cC8Zq-5T9HnV...,My field of study is data science and being ac...,I delved into data science for quite some time...,Linkedin And Facebook. I Follow Aitronix On Bo...,After Noon,Allaitopics,"Just a quick note, i was under the guidance of..."
49,2026-01-23 20:42:25.381,Samaa Mohamed saeed,01061209654,samaahassanein@gmail.com,Offline,https://www.linkedin.com/in/samaa-hassanein-7a...,https://drive.google.com/open?id=1CoYT0cKbwEt-...,To develop my knowledge and skills and I want ...,You should accept me because I am highly motiv...,"I Heard About You Through Aitronix, As I Previ...",Any time is ok,Allaitopics,Thank you for reviewing my application. I am t...
70,2026-01-23 23:01:04.430,Youssef Fawzy Shaaban,01556436636,yousseffawzy168@gmail.com,Online,www.linkedin.com/in/youssef-fawzy-ai,https://drive.google.com/open?id=12-L3zowdf8O5...,انا مهتم جدا بمجال aiجربت حجات تانيه بس لقيت ن...,عشان انا بستمر في اي حاجه بتعلمها وبلتزم فيها ...,جروب Aitronix Internship,After Noon,Allaitopics,اختروني
94,2026-01-24 02:56:41.392,Omar Fesal Abdelaziz,01145624969,omarfesal4789@gmail.com,Online,https://www.linkedin.com/in/omarfesal1,https://drive.google.com/open?id=1XYjiUoENhPjZ...,Iam interested with it and i want to learn mor...,I bring a solid foundation in System Administr...,Aitronix,Night,Allaitopics,Thank you
111,2026-01-24 14:26:08.497,تقى محمد عاطف رجب محمد احمد,01118681890,tukkaatef152@gmail.com,Online,https://www.linkedin.com/in/tukka-mohamed-b042...,https://drive.google.com/open?id=1QZX65LngZRFC...,i am interested in AI track and how it used in...,I’m a motivated and hardworking student who ta...,Post On Facebook From Aitronix,Morning,"Pythonbasics,Mathematics,Datapreprocessing,Dat...",NaN
133,2026-01-24 20:09:17.086,Ahmed Ayman,01150365179,sirahmedayman@gmail.com,Hybrid,https://www.linkedin.com/in/‪ahmed-ayman‬‏-3a9...,https://drive.google.com/open?id=1Piu0_z9j-Xyz...,"I want to improve my skills further, get a sui...",I have solid experience in coding and strong p...,Aitronix,After Noon,"Mathematics,Introductiontodataengineering(Theo...",nothing
147,2026-01-25 13:38:17.261,Ahmed shaaban Allam,01122747089,shabban811@gmail.com,Online,https://www.linkedin.com/in/ahmed-allam-1394b1...,https://drive.google.com/open?id=1QZWbzYKfp83k...,I want this scholarship because I’ve reached a...,because I am highly motivated and ready to put...,Eng. Ahmed From Aitronix,Night,Allaitopics,No thanks
184,2026-01-27 19:09:51.742,yousef mohammed abdelkareem,01123277241,Yousef.Ibrahim.2230238@CIT.hnu.edu.eg,Online,www.linkedin.com/in/joox,https://drive.google.com/open?id=1wcTL2iRTbBue...,I am deeply passionate about artificial intell...,\nI bring a strong technical foundation in AI ...,From Linked In Aitronix,Any time is ok,"Deeplearning,Mlops(Usingawsand/Orhuwawiecloud)...","I am particularly interested in MLOps, Agentic..."
213,2026-01-29 22:21:43.969,Mohamed Gamal Askar,01102644939,mg.askar.ai@gmail.com,Hybrid,https://www.linkedin.com/in/mohamedgamalaskar/,https://drive.google.com/open?id=1f-xh7TMvVtfx...,"""أنا طول عمري مهتم جداً بمجال رؤية الحاسبCompu...",الحقيقة أنا مش مجرد خريج كمبيوتر ساينس جايب تق...,Aitronix,Any time is ok,"Mlops(Usingawsand/Orhuwawiecloud),Nlp&Llms,Com...",شكرا
219,2026-01-30 05:01:05.541,Sultan Ahmed Mostafa,01276002957,sultan393493@gmail.com,Online,https://www.linkedin.com/in/sultan-a7med,https://drive.google.com/open?id=1yTm911Y0-b3v...,I am a final-year Artificial Intelligence stud...,You should accept me because I am eager to lea...,I Heard About You Through Engineer Ahmed Hafez...,Any time is ok,"Datapreprocessing,Dataanalysis(Usingpython),Ma...",I really need this course to help me gain prac...
286,2026-02-11 15:16:25.922,Bassim nabil mansour,01550403442,basimnabilmansour@gmail.com,Online,www.linkedin.com/in/bassim-nabil-53b57b328,https://drive.google.com/open?id=1ppk_4Ccq_PBC...,i want to upgrade my skills and knowleage in A...,I have gained a good skills in data analysis a...,Ai And Data Science Course With Aitronix,Night,"Mathematics,Datapreprocessing,Dataanalysis(Usi...",NO
361,2026-02-15 16:32:50.437,Omnia Hussein Ali Abdallah,01061383753,omnia.hussein.ali.95@gmail.com,Hybrid,https://www.linkedin.com/in/omnia-hussein-6480...,https://drive.google.com/open?id=1arNTct26z8OY...,I want this scholarship because I’m really int...,I’m serious about learning and I always commit...,I Heard About This Scholarship Through Linkedi...,Night,Allaitopics,No.
368,2026-02-16 22:19:28.656,Asmaa Essam Mohamed Mahmoud,01062323780,asmaaessam2005@gmail.com,Hybrid,https://www.linkedin.com/in/asmaa-essam-19bb5b...,https://drive.google.com/open?id=1is2KvaZOB-3_...,This scholarship represents a valuable opportu...,Since I am very passionate about data science ...,Linkedin - Aitronix,Any time is ok,"Pythonbasics,Mathematics,Datapreprocessing,Dat...",Thank you for considering my application and f...
378,2026-02-19 08:32:13.999,Mohamed Ahmed Mohamed Abd El-aziz,01224251326,mohamed.abdelazizz154@gmail.com,Offline,https://www.linkedin.com/in/mohamed-abd-el-azizz/,https://drive.google.com/open?id=1gvPakOG0-JT_...,Because I am serious about developing myself i...,Because I am committed to my growth and always...,"Through Linkedin, And I Also Have A Friend Who...",Any time is ok,Allaitopics,Thank you
412,2026-04-02 05:35:08.338,yousef mohammed abdelkareem,01123277241,ym9159303@gmail.com,Offline,https://www.linkedin.com/in/joox/,https://drive.google.com/open?id=1Se11E-QMzEsz...,I'm a Computer Science student at Helwan Unive...,I'm not starting from zero — I already have pr...,Aitronix Round4,Any time is ok,"Machinelearning,Deeplearning,Mlops(Usingawsand...",naaaa