In [ ]:
import pymssql
import pandas as pd 

conn = pymssql.connect(
    server='localhost',
    port=1433,
    user='sa',
    password='YourStrong!Passw0rd',
    database='master'
)

cursor = conn.cursor()

cursor.execute("SELECT name FROM sys.databases")

for row in cursor.fetchall():
    print(row)

conn.close()

('master',)
('tempdb',)
('model',)
('msdb',)
('EcommerceDB',)
('DEPI',)
('DepiRound3',)
('depi_data_engineering',)
('SalesDB',)
('sales',)
('AitroniX',)
('actula_database',)
('orders_datawarehouse',)
('SalesData',)
('sales_datewarehouse',)
('salesdatabase',)
('Sales_data_warehouse',)
('Novus',)
('eraapro',)

In [5]:
conn = pymssql.connect(
    server='localhost',
    port=1433,
    user='sa',
    password='YourStrong!Passw0rd',
    database='EcommerceDB'
)

cursor = conn.cursor()

cursor.execute("SELECT * from cart")

for row in cursor.fetchall():
    print(row)

conn.close()

(1, 1, datetime.datetime(2025, 8, 15, 0, 0), 'Active')
(2, 2, datetime.datetime(2025, 8, 15, 0, 0), 'Active')
(3, 3, datetime.datetime(2025, 8, 14, 0, 0), 'Active')
(4, 4, datetime.datetime(2025, 8, 13, 0, 0), 'Active')
(5, 5, datetime.datetime(2025, 8, 12, 0, 0), 'Active')
(6, 6, datetime.datetime(2025, 8, 11, 0, 0), 'Active')
(7, 7, datetime.datetime(2025, 8, 10, 0, 0), 'Active')
(8, 8, datetime.datetime(2025, 8, 9, 0, 0), 'Active')
(9, 9, datetime.datetime(2025, 8, 8, 0, 0), 'Active')
(10, 10, datetime.datetime(2025, 8, 7, 0, 0), 'Active')

In [14]:
conn = pymssql.connect(
    server='localhost',
    port=1433,
    user='sa',
    password='YourStrong!Passw0rd',
    database='EcommerceDB'
)

cursor = conn.cursor()


tables_query = """SELECT TABLE_NAME 
FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_TYPE = 'BASE TABLE';""" 

cursor.execute(tables_query)

tables = [ ]
for row in cursor.fetchall():
    tables.append(row[0])

In [15]:
tables

['Employees',
 'Customers',
 'Addresses',
 'Categories',
 'Brands',
 'Suppliers',
 'Products',
 'Warehouses',
 'Inventory',
 'Orders',
 'OrderItems',
 'Payments',
 'Shipments',
 'Returns',
 'Reviews',
 'Coupons',
 'Cart',
 'CartItems',
 'Wishlist']

In [16]:
EcommerceDB = dict()

for table in tables: 
    query = f"SELECT * from {table}"
    EcommerceDB[table] = pd.read_sql(query, conn)

/var/folders/_r/3sb29fjj12d916yfxyrhd_gc0000gn/T/ipykernel_85953/3218574774.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  EcommerceDB[table] = pd.read_sql(query, conn)

In [17]:
type(EcommerceDB)

dict

In [18]:
EcommerceDB["Employees"]

,EmployeeID,FirstName,LastName,Department,JobTitle,HireDate,Salary
0,1,Ahmed,Mostafa,Sales,Sales Manager,2023-01-15,25000.0
1,2,Omar,Hassan,Sales,Sales Representative,2023-04-10,12000.0
2,3,Sara,Ali,Marketing,Marketing Manager,2023-02-20,22000.0
3,4,Mariam,Khaled,Customer Service,Customer Support Specialist,2023-06-01,10000.0
4,5,Karim,Tarek,Warehouse,Warehouse Manager,2022-11-15,18000.0
5,6,Youssef,Samir,Warehouse,Inventory Specialist,2024-01-10,11000.0
6,7,Nour,Adel,Finance,Accountant,2023-03-05,15000.0
7,8,Mahmoud,Ibrahim,IT,System Administrator,2022-09-20,20000.0
8,9,Aya,Sherif,Marketing,Digital Marketing Specialist,2024-02-15,13000.0
9,10,Mostafa,Nabil,Operations,Operations Manager,2022-07-01,23000.0

In [19]:
def Read_Database( database_name ) : 
    conn = pymssql.connect(
    server='localhost',
    port=1433,
    user='sa',
    password='YourStrong!Passw0rd',
    database= database_name )

    cursor = conn.cursor()

    tables_query = """SELECT TABLE_NAME 
    FROM INFORMATION_SCHEMA.TABLES 
    WHERE TABLE_TYPE = 'BASE TABLE';""" 

    cursor.execute(tables_query)

    tables = [ ]
    for row in cursor.fetchall():
        tables.append(row[0])

    database = dict()

    for table in tables: 
        query = f"SELECT * from {table}"
        database[table] = pd.read_sql(query, conn)

    conn.close()
    return database

In [21]:
DEPI_Database = Read_Database( "DEPI" )

/var/folders/_r/3sb29fjj12d916yfxyrhd_gc0000gn/T/ipykernel_85953/2523741265.py:25: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  database[table] = pd.read_sql(query, conn)

In [23]:
DEPI_Database["Departments"]

   DepartmentID DepartmentName
0             1             HR

In [24]:
sales_Database = Read_Database( "sales" )

/var/folders/_r/3sb29fjj12d916yfxyrhd_gc0000gn/T/ipykernel_85953/2523741265.py:25: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  database[table] = pd.read_sql(query, conn)

In [25]:
sales_Database["customer"]

   customerid   customername phonenumber             emil         city country
0           5  Alice Johnson  0109243454   alice@mail.com     New York     USA
1           6      Bob Smith  0192343454     bob@mail.com  Los Angeles     USA
2           7  Carlos Rivera   019243454  carlos@mail.com       Madrid   Spain
3           8    Dina Khaled  0109243454    dina@mail.com        Cairo   Egypt

In [26]:
sales_Database["orders"]

   orderid  customerid   orderdate
0        3           5  2025-08-01
1        4           6  2025-08-02
2        5           7  2025-08-03
3        6           8  2025-08-04
4        7           8  2025-08-05

In [27]:
print(sales_Database["orders"])

   orderid  customerid   orderdate
0        3           5  2025-08-01
1        4           6  2025-08-02
2        5           7  2025-08-03
3        6           8  2025-08-04
4        7           8  2025-08-05

In [28]:
for table in sales_Database : 
    print(table)
    print(sales_Database[table])

customer
   customerid   customername phonenumber             emil         city country
0           5  Alice Johnson  0109243454   alice@mail.com     New York     USA
1           6      Bob Smith  0192343454     bob@mail.com  Los Angeles     USA
2           7  Carlos Rivera   019243454  carlos@mail.com       Madrid   Spain
3           8    Dina Khaled  0109243454    dina@mail.com        Cairo   Egypt
products
   productid     prodcutname     Category   price
0          1          Laptop  Electronics  1200.0
1          2      Smartphone  Electronics   800.0
2          3      Desk Chair    Furniture   150.0
3          4  Coffee Machine   Appliances   250.0
orders
   orderid  customerid   orderdate
0        3           5  2025-08-01
1        4           6  2025-08-02
2        5           7  2025-08-03
3        6           8  2025-08-04
4        7           8  2025-08-05
orderdetails
   orderdetailid  orderid  productid  quantity
0              2        3          1         1
1              3        3          3         2
2              4        4          2         1
3              5        4          4         1
4              6        5          2         2
5              7        6          1         1
6              8        7          3         2

In [29]:
Read_Database( "sales" )

/var/folders/_r/3sb29fjj12d916yfxyrhd_gc0000gn/T/ipykernel_85953/2523741265.py:25: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  database[table] = pd.read_sql(query, conn)

{'customer':    customerid   customername phonenumber             emil         city country
 0           5  Alice Johnson  0109243454   alice@mail.com     New York     USA
 1           6      Bob Smith  0192343454     bob@mail.com  Los Angeles     USA
 2           7  Carlos Rivera   019243454  carlos@mail.com       Madrid   Spain
 3           8    Dina Khaled  0109243454    dina@mail.com        Cairo   Egypt,
 'products':    productid     prodcutname     Category   price
 0          1          Laptop  Electronics  1200.0
 1          2      Smartphone  Electronics   800.0
 2          3      Desk Chair    Furniture   150.0
 3          4  Coffee Machine   Appliances   250.0,
 'orders':    orderid  customerid   orderdate
 0        3           5  2025-08-01
 1        4           6  2025-08-02
 2        5           7  2025-08-03
 3        6           8  2025-08-04
 4        7           8  2025-08-05,
 'orderdetails':    orderdetailid  orderid  productid  quantity
 0              2        3          1         1
 1              3        3          3         2
 2              4        4          2         1
 3              5        4          4         1
 4              6        5          2         2
 5              7        6          1         1
 6              8        7          3         2}

In [31]:
from IPython.display import display

In [32]:
for table in sales_Database : 
    display(sales_Database[table])

   customerid   customername phonenumber             emil         city country
0           5  Alice Johnson  0109243454   alice@mail.com     New York     USA
1           6      Bob Smith  0192343454     bob@mail.com  Los Angeles     USA
2           7  Carlos Rivera   019243454  carlos@mail.com       Madrid   Spain
3           8    Dina Khaled  0109243454    dina@mail.com        Cairo   Egypt

   productid     prodcutname     Category   price
0          1          Laptop  Electronics  1200.0
1          2      Smartphone  Electronics   800.0
2          3      Desk Chair    Furniture   150.0
3          4  Coffee Machine   Appliances   250.0

   orderid  customerid   orderdate
0        3           5  2025-08-01
1        4           6  2025-08-02
2        5           7  2025-08-03
3        6           8  2025-08-04
4        7           8  2025-08-05

   orderdetailid  orderid  productid  quantity
0              2        3          1         1
1              3        3          3         2
2              4        4          2         1
3              5        4          4         1
4              6        5          2         2
5              7        6          1         1
6              8        7          3         2